### ISSUE TITLE
Builds for Pytorch 2.4 (CUDA 12.1)?

### ISSUE THREAD

**Issue by chi0tzp** [facebookresearch/xformers#1044]
Hi, I was wondering whether/when you plan to release builds for **PyTorch 2.4 (CUDA 12.1)**, since I've been trying to build from source but been always failing -- FWIW error(s) are as follows:
```
  cwd: /tmp/pip-install-5ad0h0e7/xformers_8cfb69fcd26c47a094c4603071b3d6b2/
  Building wheel for xformers (setup.py) ... error
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
  Running command python setup.py clean
  running clean
  'build/lib.linux-x86_64-cpython-310' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.10' does not exist -- can't clean it
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects
```

Many thanks!

**Comment by danthe3rd** [comment]
Hi,
PyTorch 2.4 is not released yet, it's only available for nightlies. We will have a build when it's released.

**Comment by chi0tzp** [comment]
Hi @danthe3rd, thanks for the response!

**Comment by ashleykleynhans** [comment]
Hi @chi0tzp , please reopen this issue - pytorch 2.4.0 has been released but there are no xformers wheels available for it yet.  When I install xformers 0.0.27, it downgrades pytorch to version 2.3.1.

**Comment by lw** [comment]
We literally just submitted the commit to trigger builds for 2.4.0: https://github.com/fairinternal/xformers/commit/3bd420f4f9a8089a066bbee81258da34c7b445c8

Please wait a bit (<1h) and they should be available.

**Comment by ashleykleynhans** [comment]
Thanks @lw , I got the update like 1 minute after I posted my comment, thanks for getting the update out so quickly, you guys are on the ball and it is very much appreciated, thank you and keep up the amazing work!

**Comment by ashleykleynhans** [comment]
I just successfully installed xformers 0.0.27.post1 with torch 2.4.0, thank you! 🥳
