### ISSUE TITLE
WHY Performance regression with xformers 0.27.post2 + cuda 2.4.0+cu121 on old NVIDIA GPU?

### ISSUE THREAD

**Issue by motolo** [facebookresearch/xformers#1075]
# ❓ Questions and Help
On my 1060+6gb vram card I noticed a significant drop in performance during the generation phase with COMFYUI despite everything being perfectly configured, same operating temperatures, same vram used, same frequencies in the GPU.

 I can understand that my video card is old but going from 17 seconds for a generation with the default workflow to 1:21 indicates that there is something wrong both in xformers and in pytorch.

 Do you have any idea why all this could happen?
![Schermata_20240730_114113](https://github.com/user-attachments/assets/675d8743-f03b-4546-8794-f4fc841be1a6)

**Comment by lw** [comment]
Could you elaborate on why you believe this issue is caused by xFormers?

**Comment by motolo** [comment]
Because even with version 2.31 with xformers 0.27 I have the exact same problem.

**Comment by motolo** [comment]
It could also be a combination of both factors...I ask you for help or to know if anyone else has had the same problem.

**Comment by motolo** [comment]
Trovata la soluzione....aggiornare cuda alla versione 12.4:)

**Comment by motolo** [comment]
Found the solution....update cuda to version 12.4 :)
