### ISSUE TITLE
unable to pip install 0.0.28.post1 on windows

### ISSUE THREAD

**Issue by ajkessel** [facebookresearch/xformers#1104]
This is in a conda environment on Python 3.9.16.
```
  xformers\csrc\swiglu\swiglu_op.cpp(15): error C2039: 'optional': is not a member of 'std'
  C:\apps\conda\envs\voicecraft\lib\site-packages\torch\include\ATen/core/dispatch/Dispatcher.h(730): note: see declaration of 'std'
  xformers\csrc\swiglu\swiglu_op.cpp(15): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
  xformers\csrc\swiglu\swiglu_op.cpp(15): error C2143: syntax error: missing ',' before '<'
  xformers\csrc\swiglu\swiglu_op.cpp(20): error C2065: 'w1': undeclared identifier
```
Log attached.
[pip compile error.txt](https://github.com/user-attachments/files/17048861/pip.compile.error.txt)

**Comment by lw** [comment]
I'd guess you have a C++ compiler which doesn't support the C++-17 standard. Indeed, in your logs I can see this line:
```
  cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
```
I'm not familiar with Windows environments, thus I don't know if the issue is that the compiler is too old (it appears to be version 14.41.34120, dating from 2022) or whether the options given to it are incorrect.

Could you attempt to modify the setup.py to replace all instances of `-std=c++17` with `/std:c++17`?

**Comment by lw** [comment]
Actually, can you also just try adding `#include <optional>` at the beginning of swiglu_op.cpp?

**Comment by ajkessel** [comment]
Weirdly, I'm not able to reproduce the issue now. I have created fresh conda environments since first reporting this bug, both with python 3.9.16 and 3.12.3, and successfully installed transformers in both. It is no longer trying to build from source, though, and instead seems to be finding a pre-built version.

I cloned the repo and tried to force a manual build with `pip install -e ./` but get:
```
Traceback (most recent call last):
  File "C:\apps\src\sandbox\xformers\setup.py", line 674, in <module>
    symlink_package(
  File "C:\apps\src\sandbox\xformers\setup.py", line 128, in symlink_package
    shutil.copytree(src=path_from, dst=path_to)
  File "C:\apps\conda\envs\vall\Lib\shutil.py", line 598, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\apps\\src\\sandbox\\xformers\\third_party\\flash-attention\\flash_attn'

**Comment by ajkessel** [comment]
Weirdly, I'm not able to reproduce the issue now. I have created fresh conda environments since first reporting this bug, both with python 3.9.16 and 3.12.3, and successfully installed xformers in both. It is no longer trying to build from source, though, and instead seems to be finding a pre-built version.

I cloned the repo and tried to force a manual build with `pip install -e ./` but get:
```
Traceback (most recent call last):
  File "C:\apps\src\sandbox\xformers\setup.py", line 674, in <module>
    symlink_package(
  File "C:\apps\src\sandbox\xformers\setup.py", line 128, in symlink_package
    shutil.copytree(src=path_from, dst=path_to)
  File "C:\apps\conda\envs\vall\Lib\shutil.py", line 598, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\apps\\src\\sandbox\\xformers\\third_party\\flash-attention\\flash_attn'
```

Am I going about this the wrong way?

**Comment by lw** [comment]
Make sure you cloned all submodules. Either add `--recursive` to `git clone`, or do `git submodule update --init --recursive` to an already cloned repo.

**Comment by ajkessel** [comment]
That worked! And it compiles successfully. Strangely I cannot recreate the problem any more, so I guess if no one else has it, we can close.
