### ISSUE TITLE
what version about torch in FLUX bf16？

### ISSUE THREAD

**Issue by Zhuangvictor0** [facebookresearch/xformers#1111]
# ❓ Questions and Help
my environment:A100 GRAM40G ,72 G vram
when I try to run python app_flux.py --aggressive_offload --onnx_provider cpu, it killed, what's the real problem of it?
<img width="758" alt="image" src="https://github.com/user-attachments/assets/c15b42e6-e4a5-440d-8082-c8149079635c">

**Comment by lw** [comment]
Why do you believe this is an issue with xFormers? The log message you posted says that you don't even have xFormers installed.
