### ISSUE TITLE
Are there any version for Torch 2.5 including dev? like 0.0.29.dev921?

### ISSUE THREAD

**Issue by FurkanGozukara** [facebookresearch/xformers#1121]
I tried this but it fails and can't find wheel where to download

pip3 install xformers==0.0.29.dev921 --index-url https://download.pytorch.org/whl/cu124

**Comment by Piscabo** [comment]
Need the updated version of Xformers please:
pytorch version: 2.5.0+cu124
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.1+cu124 with CUDA 1204 (you have 2.5.0+cu124)
    Python  3.11.9 (you have 3.11.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.28.post1

**Comment by timothelaborie** [comment]
Can someone make a wheel with pytorch 2.5 and CUDA 12.6?

**Comment by alex13by** [comment]
There is an attempt to install xformers==0.0.29.dev924, but comfyui doesn't work. It seems that this version of xformers doesn't support torch2.5.0

**Comment by lw** [comment]
We're working on supporting PyTorch 2.5.

On the other hand, we will not provide builds for CUDA 12.6 yet because they aren't provided by PyTorch either.

**Comment by VRVirtuosos** [comment]
Is there any update on this , also having this issue.

**Comment by lw** [comment]
v0.0.28.post2 supports PyTorch 2.5.0 and v0.0.28.post3 supports PyTorch 2.5.1.

In the future please look at our changelog for this kind of information: https://github.com/facebookresearch/xformers/blob/main/CHANGELOG.md
