### ISSUE TITLE
AMD64 version of Xformers

### ISSUE THREAD

**Issue by pandayummy** [facebookresearch/xformers#1130]
https://pypi.org/project/xformers/0.0.29.dev925/#files

Can we have 
xformers-0.0.29.dev925-cp312-cp312-amd64

**Comment by pandayummy** [comment]
forget it, I switched to python 3.11.

**Comment by zslefour** [comment]
> https://pypi.org/project/xformers/0.0.29.dev925/#files
> 
> Can we have xformers-0.0.29.dev925-cp312-cp312-amd64

Can you share it with me, I didn't succeed in compiling, thanks
