### ISSUE TITLE
torch2.5.1 support

### ISSUE THREAD

**Issue by luohao123** [facebookresearch/xformers#1137]
does torch2.5.1 can using conda to install?

**Comment by lw** [comment]
We're working on builds for 2.5.1, stay tuned

**Comment by luohao123** [comment]
Is that possible make xformers synced with torch official stable release? Once torch released their new stable version, xformers should have one, for both cuda 12.1 and 12.4 for the moment.

How do u guys think?

**Comment by lw** [comment]
That would be nice. How do you suggest we achieve that?

BTW the builds for PyTorch 2.5.1 are out, closing.
