### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by algorithmconquer** [facebookresearch/xformers#1154]
The error is :
python3.10/site-packages/diffusers/models/transformers/transformer_flux.py", line 180, in forward
    attn_output, context_attn_output = self.attn(
ValueError: not enough values to unpack (expected 2, got 1)...

diffusers==0.32.0.dev0
torch==2.5.1
xformers==0.0.28.post3
transformers==4.46.2

**Comment by lw** [comment]
The error seems to come from diffusers, not from xFormers.
