### ISSUE TITLE
Triton Module Not Available: xformers Optimizations Failing on Windows with CUDA 12.4

### ISSUE THREAD

**Issue by BasimBashir** [facebookresearch/xformers#1156]
# 🐛 Bug

A matching Triton is not available, so some optimizations are not enabled when using xformers. This results in the following error message:

```
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\mianx\OneDrive\Desktop\Stable_Diffusion_App\.venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
```

## Command
```
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu124
```

## To Reproduce

1. Install xformers using the command: `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu124`
2. Use the xformers library with PyTorch and the diffusers package for image generation on a Windows system with Python 3.10.11 and CUDA 12.4.
3. Observe the reported error about Triton not being available.

## Expected behavior

The Triton module should be available and integrated with xformers to enable its optimizations, resulting in improved performance for tasks like image generation using the diffusers package. These optimizations are essential for achieving faster results, particularly on Windows-based systems.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (2.5.1)
- OS (Windows 10)
- How you installed PyTorch (`pip`)
- Python version (3.10.11)
- CUDA/cuDNN version (CUDA 12.4, cuDNN 9.5)
- GPU models and configuration (NVIDIA GeForce RTX 3090) 
- Any other relevant information (xformers is installed via the PyTorch-provided index URL for CUDA 12.4.)
- Below is attached, the outputs of: `python -m torch.utils.collect_env`
```
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Could not collect
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.26100-SP0
Is CUDA available: True
CUDA runtime version: 12.6.77
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 566.14
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] onnxruntime==1.19.2
[pip3] torch==2.5.1+cu124
[pip3] torchao==0.1
[pip3] torchaudio==2.5.1+cu124
[pip3] torchvision==0.20.1+cu124
[conda] Could not collect
```

## Additional context

I am using the xformers library to accelerate image generation tasks with the diffusers package. The Triton module is critical for enabling certain optimizations in xformers, which can greatly benefit developers working on Windows systems by enhancing the performance of these tasks.

Please let me know if there are additional steps or configurations required to resolve this issue. Thank you!

**Comment by lw** [comment]
The "error" you're reporting is actually just a warning. Please be clear about what isn't working for you.

Also, Triton needs to be installed separately, it's not bundled with xFormers.
