### ISSUE TITLE
  Building wheel for xformers (setup.py) ... error

### ISSUE THREAD

**Issue by tiandaoyuxi** [facebookresearch/xformers#1168]
# 🐛 Bug

D:\Comfy_UI>python_embeded\python.exe -m pip install xformers
Collecting xformers
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.4 in d:\comfy_ui\python_embeded\lib\site-packages (from xformers) (2.5.1+cu121)
Requirement already satisfied: numpy in d:\comfy_ui\python_embeded\lib\site-packages (from xformers) (1.26.4)
Requirement already satisfied: filelock in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (4.12.2)
Requirement already satisfied: networkx in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (3.3)
Requirement already satisfied: jinja2 in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (3.1.4)
Requirement already satisfied: fsspec in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (2024.6.1)
Requirement already satisfied: sympy==1.13.1 in d:\comfy_ui\python_embeded\lib\site-packages (from torch>=2.4->xformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\comfy_ui\python_embeded\lib\site-packages (from sympy==1.13.1->torch>=2.4->xformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\comfy_ui\python_embeded\lib\site-packages (from jinja2->torch>=2.4->xformers) (2.1.5)
Building wheels for collected packages: xformers
  Building wheel for xformers (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [290 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-311\xformers
      copying xformers\attn_bias_utils.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\checkpoint.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\info.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\test.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\utils.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\_cpp_lib.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\_deprecation_warning.py -> build\lib.win-amd64-cpython-311\xformers
      copying xformers\__init__.py -> build\lib.win-amd64-cpython-311\xformers
      creating build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_attn_decoding.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_core.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_indexing.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_mem_eff_attention.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_merge_attentions.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_multi_head_dispatch.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_nystrom_utils.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_revnet.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_sddmm.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_sequence_parallel_fused.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_sp24.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_swiglu.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\benchmark_tiled_matmul.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\utils.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      copying xformers\benchmarks\__init__.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks
      creating build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\activations.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\input_projection.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\multi_head_dispatch.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\patch_embedding.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\residual.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\reversible.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\simplicial_embedding.py -> build\lib.win-amd64-cpython-311\xformers\components
      copying xformers\components\__init__.py -> build\lib.win-amd64-cpython-311\xformers\components
      creating build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\block_configs.py -> build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\block_factory.py -> build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\hydra_helper.py -> build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\model_factory.py -> build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\weight_init.py -> build\lib.win-amd64-cpython-311\xformers\factory
      copying xformers\factory\__init__.py -> build\lib.win-amd64-cpython-311\xformers\factory
      creating build\lib.win-amd64-cpython-311\xformers\helpers
      copying xformers\helpers\hierarchical_configs.py -> build\lib.win-amd64-cpython-311\xformers\helpers
      copying xformers\helpers\test_utils.py -> build\lib.win-amd64-cpython-311\xformers\helpers
      copying xformers\helpers\timm_sparse_attention.py -> build\lib.win-amd64-cpython-311\xformers\helpers
      copying xformers\helpers\__init__.py -> build\lib.win-amd64-cpython-311\xformers\helpers
      creating build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\common.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\differentiable_collectives.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\indexing.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\ipc.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\modpar_layers.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\rmsnorm.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\rope_padded.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\seqpar.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\sequence_parallel_fused_ops.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\sp24.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\swiglu_op.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\tiled_matmul.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\unbind.py -> build\lib.win-amd64-cpython-311\xformers\ops
      copying xformers\ops\__init__.py -> build\lib.win-amd64-cpython-311\xformers\ops
      creating build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\api.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\device_limits.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\find_slowest.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\profiler.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\profiler_dcgm.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\profiler_dcgm_impl.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\profile_analyzer.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      copying xformers\profiler\__init__.py -> build\lib.win-amd64-cpython-311\xformers\profiler
      creating build\lib.win-amd64-cpython-311\xformers\sparse
      copying xformers\sparse\blocksparse_tensor.py -> build\lib.win-amd64-cpython-311\xformers\sparse
      copying xformers\sparse\csr_tensor.py -> build\lib.win-amd64-cpython-311\xformers\sparse
      copying xformers\sparse\utils.py -> build\lib.win-amd64-cpython-311\xformers\sparse
      copying xformers\sparse\_csr_ops.py -> build\lib.win-amd64-cpython-311\xformers\sparse
      copying xformers\sparse\__init__.py -> build\lib.win-amd64-cpython-311\xformers\sparse
      creating build\lib.win-amd64-cpython-311\xformers\triton
      copying xformers\triton\vararg_kernel.py -> build\lib.win-amd64-cpython-311\xformers\triton
      copying xformers\triton\__init__.py -> build\lib.win-amd64-cpython-311\xformers\triton
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\bert_padding.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\flash_attn_interface.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\flash_attn_triton.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\flash_attn_triton_og.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\flash_blocksparse_attention.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\flash_blocksparse_attn_interface.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\fused_softmax.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      copying xformers\_flash_attn\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn
      creating build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\batch_fetch_results.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\batch_submit.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\run_grid_search.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\run_tasks.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\run_with_submitit.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      copying xformers\benchmarks\LRA\__init__.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA
      creating build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA\code
      copying xformers\benchmarks\LRA\code\dataset.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA\code
      copying xformers\benchmarks\LRA\code\model_wrapper.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA\code
      copying xformers\benchmarks\LRA\code\__init__.py -> build\lib.win-amd64-cpython-311\xformers\benchmarks\LRA\code
      creating build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\attention_mask.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\attention_patterns.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\base.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\compositional.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\core.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\favor.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\fourier_mix.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\global_tokens.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\lambda_layer.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\linformer.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\local.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\nystrom.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\ortho.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\pooling.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\random.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\scaled_dot_product.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\sparsity_config.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\utils.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\visual.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\_sputnik_sparse.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      copying xformers\components\attention\__init__.py -> build\lib.win-amd64-cpython-311\xformers\components\attention
      creating build\lib.win-amd64-cpython-311\xformers\components\feedforward
      copying xformers\components\feedforward\base.py -> build\lib.win-amd64-cpython-311\xformers\components\feedforward
      copying xformers\components\feedforward\conv_mlp.py -> build\lib.win-amd64-cpython-311\xformers\components\feedforward
      copying xformers\components\feedforward\mixture_of_experts.py -> build\lib.win-amd64-cpython-311\xformers\components\feedforward
      copying xformers\components\feedforward\mlp.py -> build\lib.win-amd64-cpython-311\xformers\components\feedforward
      copying xformers\components\feedforward\__init__.py -> build\lib.win-amd64-cpython-311\xformers\components\feedforward
      creating build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\base.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\param.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\rotary.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\sine.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\vocab.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      copying xformers\components\positional_embedding\__init__.py -> build\lib.win-amd64-cpython-311\xformers\components\positional_embedding
      creating build\lib.win-amd64-cpython-311\xformers\components\attention\feature_maps
      copying xformers\components\attention\feature_maps\base.py -> build\lib.win-amd64-cpython-311\xformers\components\attention\feature_maps
      copying xformers\components\attention\feature_maps\softmax.py -> build\lib.win-amd64-cpython-311\xformers\components\attention\feature_maps
      copying xformers\components\attention\feature_maps\__init__.py -> build\lib.win-amd64-cpython-311\xformers\components\attention\feature_maps
      creating build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\attn_bias.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\ck.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\ck_decoder.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\ck_splitk.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\common.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\cutlass.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\dispatch.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\flash.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\flash3.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\torch_attention_compat.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\triton_splitk.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      copying xformers\ops\fmha\__init__.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha
      creating build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\k_index_select_cat.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\k_scaled_index_add.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\rmsnorm_kernels.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\rope_padded_kernels.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\tiled_matmul_kernels.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      copying xformers\ops\_triton\__init__.py -> build\lib.win-amd64-cpython-311\xformers\ops\_triton
      creating build\lib.win-amd64-cpython-311\xformers\ops\fmha\_triton
      copying xformers\ops\fmha\_triton\splitk_kernels.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha\_triton
      copying xformers\ops\fmha\_triton\__init__.py -> build\lib.win-amd64-cpython-311\xformers\ops\fmha\_triton
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\layers
      copying xformers\_flash_attn\layers\patch_embed.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\layers
      copying xformers\_flash_attn\layers\rotary.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\layers
      copying xformers\_flash_attn\layers\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\layers
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\losses
      copying xformers\_flash_attn\losses\cross_entropy.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\losses
      copying xformers\_flash_attn\losses\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\losses
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\baichuan.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\bert.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\bigcode.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\btlm.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\falcon.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\gpt.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\gptj.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\gpt_neox.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\llama.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\opt.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\vit.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      copying xformers\_flash_attn\models\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\models
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      copying xformers\_flash_attn\modules\block.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      copying xformers\_flash_attn\modules\embedding.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      copying xformers\_flash_attn\modules\mha.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      copying xformers\_flash_attn\modules\mlp.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      copying xformers\_flash_attn\modules\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\modules
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      copying xformers\_flash_attn\ops\activations.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      copying xformers\_flash_attn\ops\fused_dense.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      copying xformers\_flash_attn\ops\layer_norm.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      copying xformers\_flash_attn\ops\rms_norm.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      copying xformers\_flash_attn\ops\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      copying xformers\_flash_attn\utils\benchmark.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      copying xformers\_flash_attn\utils\distributed.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      copying xformers\_flash_attn\utils\generation.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      copying xformers\_flash_attn\utils\pretrained.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      copying xformers\_flash_attn\utils\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\utils
      creating build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\cross_entropy.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\k_activations.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\layer_norm.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\linear.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\mlp.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\rotary.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      copying xformers\_flash_attn\ops\triton\__init__.py -> build\lib.win-amd64-cpython-311\xformers\_flash_attn\ops\triton
      running build_ext
      D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py:416: UserWarning: The detected CUDA version (12.6) has a minor version mismatch with the version that was used to compile PyTorch (12.1). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      building 'xformers._C_flashattention' extension
      creating C:\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\build\temp.win-amd64-cpython-311\Release\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\third_party\flash-attention\csrc\flash_attn
      creating C:\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\build\temp.win-amd64-cpython-311\Release\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\third_party\flash-attention\csrc\flash_attn\src
      Emitting ninja build file C:\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\build\temp.win-amd64-cpython-311\Release\build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      ninja: error: Stat(C:/Users/win11/AppData/Local/Temp/pip-install-cusdawns/xformers_b32183b030ee4a28bd49e949821d1b53/build/temp.win-amd64-cpython-311/Release/Users/win11/AppData/Local/Temp/pip-install-cusdawns/xformers_b32183b030ee4a28bd49e949821d1b53/third_party/flash-attention/csrc/flash_attn/flash_api.obj): Filename longer than 260 characters
      Traceback (most recent call last):
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
          subprocess.run(
        File "subprocess.py", line 571, in run
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\setup.py", line 680, in <module>
          setuptools.setup(
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\command\bdist_wheel.py", line 381, in run
          self.run_command("build")
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\dist.py", line 995, in run_command
          super().run_command(command)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\command\build_ext.py", line 99, in run
          _build_ext.run(self)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 359, in run
          self.build_extensions()
        File "C:\Users\win11\AppData\Local\Temp\pip-install-cusdawns\xformers_b32183b030ee4a28bd49e949821d1b53\setup.py", line 637, in build_extensions
          super().build_extensions()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 868, in build_extensions
          build_ext.build_extensions(self)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 476, in build_extensions
          self._build_extensions_serial()
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 502, in _build_extensions_serial
          self.build_extension(ext)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\command\build_ext.py", line 264, in build_extension
          _build_ext.build_extension(self, ext)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\Cython\Distutils\build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 557, in build_extension
          objects = self.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 840, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1784, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "D:\Comfy_UI\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2120, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)

## To Reproduce

1.
2.
3.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by Wiselnn570** [comment]
@tiandaoyuxi I encountered the same problem. How did you solve it?

**Comment by amoyplane** [comment]
same installing xformers-0.0.28.post3.tar.gz on Linux

**Comment by tiandaoyuxi** [comment]
Sorry, it was resolved a long time ago and I forgot to close the case
I will install it directly using “xformers-0.0.28.post3-cp312-cp312-win_amd64.whl”

D:\Comfy_UI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-27 12:58:17.687085
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\Comfy_UI\python_embeded\python.exe
** ComfyUI Path: D:\Comfy_UI\ComfyUI
** Log path: D:\Comfy_UI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   5.0 seconds: D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130852 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: D:\Comfy_UI\ComfyUI\web
ASTERR config loaded successfully
Web extensions folder found at D:\Comfy_UI\ComfyUI\web\extensions\ComfyLiterals
