### ISSUE TITLE
Incompatibility with latest triton

### ISSUE THREAD

**Issue by antony-frolov** [facebookresearch/xformers#1172]
# ❓ Questions and Help

Since https://github.com/triton-lang/triton/commit/a06add016336706ebc2a061776c0c769d371a882 triton's ops got deprecated (removed) so xformers no longer works with the latest versions of triton. Are there any plans to fix the incompatibility?

For example `triton.ops` is used here https://github.com/facebookresearch/xformers/blob/5a9fc9bb1eff5bb3133ad3c3653fa2ebeaff4485/xformers/benchmarks/benchmark_tiled_matmul.py#L11

**Comment by lw** [comment]
Thanks for flagging, we're working on it

**Comment by lw** [comment]
This should be fixed by https://github.com/facebookresearch/xformers/commit/2583317c70639177e848d22c4d845374d167404a
