### ISSUE TITLE
suitable version of xformers for installation

### ISSUE THREAD

**Issue by soltaninejad** [facebookresearch/xformers#1184]
# ❓ Questions and Help
hi, i need to install xformer on my system with pytorch 1.12.1.(for some specific reason i  have to installed pytorch 1.12.1)
how can i do it? i try to do it with this command:
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
but i get error about "aten::_efficient_attention_forward", which seems there is not in my current version of pytorch.
what should i do?

**Comment by lw** [comment]
xFormers depends on the latest version of PyTorch. Since PyTorch 1.12.1 dates from over two years ago, you will need to go looking for a suitably old version of xFormers. It appears that v0.0.13 should support PyTorch 1.12.1. Note however that it will miss most of the newest features.
