### ISSUE TITLE
Incorrect implementation of `BlockDiagonalCausalMask.to(..)`

### ISSUE THREAD

**Issue by vineelwf** [facebookresearch/xformers#1185]
There is a bug in `BlockDiagonalCausalMask.to(..)` implementation from xformers. Currently, it calls the parent class function  `BlockDiagonalMask.to(..)` and returns a `BlockDiagonalMask` .

```
mask = BlockDiagonalCausalMask.from_seqlens([2, 2])
print("mask", mask.materialize([1, 4, 4]))
[[[0., -inf, -inf, -inf],
   [0., 0., -inf, -inf],
   [-inf, -inf, 0., -inf],
   [-inf, -inf, 0., 0.]]])

mask2 = mask.to(device="cuda")
print("mask2", mask2.materialize([1, 4, 4]))
[[[0., 0., -inf, -inf],
   [0., 0., -inf, -inf],
   [-inf, -inf, 0., 0.],
   [-inf, -inf, 0., 0.]]])
```

Tested on xformers version 0.0.28.post3

**Comment by danthe3rd** [comment]
Hi,
Thanks for reporting this bug. Will push a fix within a few days

**Comment by danthe3rd** [comment]
Fixed in https://github.com/facebookresearch/xformers/commit/a8746f3bb3bab42aa6064b5e4ee9ba80ce0a2bcf
