### ISSUE TITLE
Sputnik in Xformers

### ISSUE THREAD

**Issue by tgale96** [facebookresearch/xformers#15]
# ❓ Questions and Help

Hello! I'm the author of Sputnik and noticed that you've forked it! I'm interested to understand your use cases. If you have any questions about the library I'm happy to help!

**Comment by tgale96** [comment]
No worries! I'm just happy to see more users :) Fine-grained sparse attention topologies is a cool use case! I'd be really curious to see what kinds of results you're able to get.

For supporting batched CSR where each matrix has its own topology I would do the following. To store the matrix I'd pack all the nonzeros/indices/offsets into the same allocations. Then I'd add another offset array to the data structure to encode the starts of each of the individual matrices. In the kernel I'd do two modifications. First, you can launch a [3D grid](https://github.com/google-research/sputnik/blob/master/sputnik/spmm/cuda_spmm.cu.cc#L582) of thread blocks, where the third dimension encodes which matrix in the batch is to be processed. Then you can wrap the [kernel device function](https://github.com/tgale96/sputnik/blob/main/sputnik/spmm/cuda_spmm.cu.cc#L106) with a small function that will a) lookup the threadblock's matrix in the batch and b) offset the pointers to the start of the sparse/dense matrices and c) call the kernel device function.

FP16 is a little tricky with Sputnik because I never got around to removing the constraint that the number of nonzeros in each row must be divisible by 2. I had another request recently to get rid of this so it seems like maybe I should finally allocate some time for it :)

That's a good point about the index limitation - I'd been primarily using them for models where the weights are sparse and it's less common to have 32k weights in one dimension. I know cuSPARSE supports 32-bit indices with fp16 data but you obviously wouldn't be able to modify these kernels. I'll have to think about what it will take to add support for 32-bit indices with 16-bit data.

Hope this helps! Looks like you've done some great work. I'm excited to look around the repo more!

Trevor

**Comment by blefaudeux** [comment]
closing that for now since it's not actively being worked on, feel free to reopen anytime !

**Comment by siddharth9820** [comment]
Hi @tgale96!
Did you get around to fixing the indexing issue for fp-16?
