### ISSUE TITLE
AttentionMask is not scriptable

### ISSUE THREAD

**Issue by erip** [facebookresearch/xformers#168]
# 🐛 Bug

`AttentionMask` and any model composed of `AttentionMask` cannot be scripted.

## To Reproduce

1. Run code as below

```python
>>> import torch
>>> from xformers.components.attention import AttentionMask
>>> bool_mask = torch.rand((256, 256)) > 0.5
>>> additive_mask = AttentionMask.from_bool(bool_mask)
>>> torch.jit.script(additive_mask)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erip/opt/miniconda3/envs/traduis-dev/lib/python3.7/site-packages/torch/jit/_script.py", line 1318, in script
    return torch.jit._recursive.create_script_class(obj)
  File "/Users/erip/opt/miniconda3/envs/traduis-dev/lib/python3.7/site-packages/torch/jit/_recursive.py", line 419, in create_script_class
    _compile_and_register_class(type(obj), rcb, qualified_class_name)
  File "/Users/erip/opt/miniconda3/envs/traduis-dev/lib/python3.7/site-packages/torch/jit/_recursive.py", line 44, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
RuntimeError:
Expression of type apply cannot be used in a type expression:
  File "/Users/erip/Code/xformers/xformers/components/attention/attention_mask.py", line 128
    def __add__(self, other):
        assert isinstance(other, type(self))
                                 ~~~~~~~~~ <--- HERE
        return AttentionMask(self.values + other.values, is_causal=False)
```

## Expected behavior

`AttentionMask` should be a JIT-able module.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.7.11 (default, Jul 27 2021, 07:03:16)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: Darwin-19.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.4
[pip3] torch==1.10.1
[pip3] torchtext==0.11.1
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] mkl                       2021.4.0           hecd8cb5_637  
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.4                   pypi_0    pypi
[conda] pytorch                   1.10.1                  py3.7_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchtext                 0.11.1                     py37    pytorch

**Comment by erip** [comment]
I have some workarounds here, but it requires some hacking that may not be acceptable for the library. Specifically:

- [`TypeVar` is not permitted in scripting](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/attention_mask.py#L11) so `s/Self/"AttentionMask"/g`
- `classmethods` must populate all arguments (including [default args](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/attention_mask.py#L26) e.g., `is_causal=False`)
- For some reason `x = x.bool()` doesn't work during JIT phsase. `x = x.to(torch.bool)` does.
- Places where `None` is coerced to a truthy/falsy value should be explicitly checked (e.g., [here](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/attention_mask.py#L81))
- Some [type assertions](https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/attention_mask.py#L128) are not kosher during JIT phase. I'm not sure how this is typically handled in scripting code...

**Comment by blefaudeux** [comment]
Hey @erip, thanks for this issue and investigation ! I think that all of your points above are actually pretty nice (or not that bad, like `x.to()`), we should probably just do that if that's all it takes. The TypeVar part should just be for MyPy I think, it's surprising that torchscript takes offense about that, on the mypy side there are workarounds. I can have a look a little later, else feel free to get a PR up, seems promising !

**Comment by erip** [comment]
Sounds good! I'll start putting a PR together and we can see how it looks. It doesn't seem like a lot of effort, so if it doesn't work out then it's not a huge loss.

**Comment by fmassa** [comment]
Hi,

Thanks for opening this issue!

Unfortunately I don't think we will be able to have most of xformers to be torchscriptable, for the following reasons:
- anything that uses triton won't be torchscriptable (block-sparse, efficient kernels)
- `torch.autograd.Function` is not torchscriptable (so the sparse ops won't be torchscriptable as is). This could be fixed, but from the following point I believe this won't be actually useful
- `__torch_function__` and tensor inheritance are not torchscriptable, so https://github.com/facebookresearch/xformers/pull/124 and the [upcoming refactoring for blocksparse](https://github.com/facebookresearch/xformers/tree/blocksparse_refactoring) won't work.

In general, I don't think we should be spending much efforts with torchscript in xformers. Indeed, torchscript scope is changing and it won't be the recommended route to go to production anymore, as `torch.package` and `torch::deploy` will replace the "deployment" part of torchscript (which will be focusing on operator fusion).

Thus, my vote would be to explictly tag xformers as non-torchscript compatible.

Thoughts?

**Comment by erip** [comment]
@fmassa thanks for the context! I actually just learned about the new package features but didn't realize it was a "direct route" to C++ --- I had assumed we'd still need to transit torchscript to get the multithreading. If you think it's better to put a stamp on the repo, that's fine. It certainly avoids some of the intrusive changes outlined above.

**Comment by blefaudeux** [comment]
> Hi,
> 
> Thanks for opening this issue!
> 
> Unfortunately I don't think we will be able to have most of xformers to be torchscriptable, for the following reasons:
> 
>     * anything that uses triton won't be torchscriptable (block-sparse, efficient kernels)
> 
>     * `torch.autograd.Function` is not torchscriptable (so the sparse ops won't be torchscriptable as is). This could be fixed, but from the following point I believe this won't be actually useful
> 
>     * `__torch_function__` and tensor inheritance are not torchscriptable, so [Introduce SparseCSRTensor as a replacement for SparseCS #124](https://github.com/facebookresearch/xformers/pull/124) and the [upcoming refactoring for blocksparse](https://github.com/facebookresearch/xformers/tree/blocksparse_refactoring) won't work.
> 
> 
> In general, I don't think we should be spending much efforts with torchscript in xformers. Indeed, torchscript scope is changing and it won't be the recommended route to go to production anymore, as `torch.package` and `torch::deploy` will replace the "deployment" part of torchscript (which will be focusing on operator fusion).
> 
> Thus, my vote would be to explictly tag xformers as non-torchscript compatible.
> 
> Thoughts?

Ah, I almost wrote that yesterday evening (probably not worth it given the custom processing which is not torchscript compatible) but then I changed my mind seeing @erip list of enablers which looked reasonable to me (I thought of the projection and other pure pytorch parts -nystrom, linformer- which could benefit from torchscript maybe). 

I did not have the extra deprecation context though, and with that I'm with you @fmassa, probably not worth it in the grand scheme of things
