### ISSUE TITLE
Does xformers support incremental decoding?

### ISSUE THREAD

**Issue by DongChanS** [facebookresearch/xformers#218]
# ❓ Questions and Help
I want to use transformer decoder for **incremental decoding**
For example, the [fairseq framework](https://github.com/pytorch/fairseq/blob/main/fairseq/models/transformer/transformer_decoder.py#L186) supports incremental decoding 

Can i use xformers for incremental decoding?

**Comment by blefaudeux** [comment]
cc @dianaml0, @iyerr3. Not yet sorry, ideally there could be an optimized part for that (ie the torch implementation from fairseq is probably slow), it's a very common request actually

**Comment by blefaudeux** [comment]
closing, the short term answer is no then, I'll defer to @dianaml0 for long term plans !
