### ISSUE TITLE
Is it safe to use mixed precision training with kernel-based attention mechanisms? 

### ISSUE THREAD

**Issue by Tomsen1410** [facebookresearch/xformers#224]
# ❓ Questions and Help

I wanted to ask whether it is safe to use e.g. nystrom or favor attention with mixed precision (or full fp16) training?

**Comment by blefaudeux** [comment]
Yes it is, it should be unit tested for most of them actually. Please report any issues !

**Comment by blefaudeux** [comment]
closing, feel free to reopen !
