### ISSUE TITLE
Layernorm & Dropout + BF16

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/xformers#286]
# 🐛 Bug
cf. https://github.com/SeanNaren/SmallScience/issues/10, layernorm seems to error out with bf16
Should not be too bad 

edit: 
- layer norm is fine
- dropout errors out indeed

**Comment by blefaudeux** [comment]
I'm having a look at dropout, there's an easy fallback (catch and cast) but this destroys the perf, I'm checking with the Triton folks whether there's a better option

**Comment by SeanNaren** [comment]
Thanks a tonne!!

**Comment by blefaudeux** [comment]
Quick update in that the work is ongoing, it's on the Triton side (well, LLVM actually) but being fixed by Phil Tillet and team

**Comment by SeanNaren** [comment]
hey @blefaudeux has there been any update at all here?

cc @ptillet as this might be fixed upstream in triton already.

**Comment by blefaudeux** [comment]
> hey @blefaudeux has there been any updates here?
> 
> cc @ptillet as this might be fixed upstream in triton already.

hey Sean, I checked a couple of weeks ago with current triton, it was crashing on a tl.max() still :/

**Comment by blefaudeux** [comment]
I just checked right now, confirmed with a minimal repro with the layernorm unit test / https://github.com/blefaudeux/xformers/tree/layernorm_bf16

**Comment by SeanNaren** [comment]
> I just checked right now, confirmed with a minimal repro with the layernorm unit test / https://github.com/blefaudeux/xformers/tree/layernorm_bf16

Thanks for checking @blefaudeux! I assume this is something we'll have to wait for the triton team to fix?

**Comment by blefaudeux** [comment]
> > I just checked right now, confirmed with a minimal repro with the layernorm unit test / https://github.com/blefaudeux/xformers/tree/layernorm_bf16
> 
> Thanks for checking @blefaudeux! I assume this is something we'll have to wait for the triton team to fix?

hey Sean, sorry for the delay, been travelling ! I can spend some time on that a bit later maybe, it looks like Triton and if I remember correctly it was actually tied to LLVM, but could well be that there are workarounds. I've been using bfloat16 a bit lately (following [this](https://github.com/Lightning-AI/lightning/issues/11933#issuecomment-1173962970) but without lightning, I can confirm that at least for some models pytorch 1.12 works fine), so I'm definitely interested myself

**Comment by SeanNaren** [comment]
> > > I just checked right now, confirmed with a minimal repro with the layernorm unit test / https://github.com/blefaudeux/xformers/tree/layernorm_bf16
> > 
> > 
> > Thanks for checking @blefaudeux! I assume this is something we'll have to wait for the triton team to fix?
> 
> hey Sean, sorry for the delay, been travelling ! I can spend some time on that a bit later maybe, it looks like Triton and if I remember correctly it was actually tied to LLVM, but could well be that there are workarounds. I've been using bfloat16 a bit lately (following [this](https://github.com/Lightning-AI/lightning/issues/11933#issuecomment-1173962970) but without lightning, I can confirm that at least for some models pytorch 1.12 works fine), so I'm definitely interested myself

There is no rush @blefaudeux! was just curious on what we're waiting for. I've managed to get around it by disabling triton anyway, lose some perf but at least it runs aha.

Regarding that issue, that's what I'm investigating :) going to use the `imagenet` example (lightning/no lightning), the `microGPT` example and a `minGPT` example to benchmark bfloat16 perf.

**Comment by blefaudeux** [comment]
should be fixed with the triton update from a few weeks ago
