### ISSUE TITLE
Abo harb he test do the hack

### ISSUE THREAD

**Issue by Hdhjsjj** [facebookresearch/xformers#291]
# 🐛 Bug

## To Reproduce

1.
2.
3.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by blefaudeux** [comment]
hmm, spam I guess ?
