### ISSUE TITLE
Support "Flash attention"

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/xformers#314]
# 🚀 Feature
See https://arxiv.org/abs/2205.14135 and https://github.com/HazyResearch/flash-attention

## Motivation
Make it easy to compare with other methods (including sparsity), make it available in general

## Pitch
Not much work in xformers, just aligning the interface (famous last words)

## Alternatives
Mem efficient attention

**Comment by tridao** [comment]
Hi Ben, we're the authors of FlashAttention here.
Would be awesome to have it supported in xformers! Let's figure out how to do it!
Btw I've personally been a fan of xformers (and we borrowed some components such as Rotary embedding https://github.com/HazyResearch/flash-attention/blob/main/src/rotary.py from your repo :D)

**Comment by tridao** [comment]
> we just pip install if/when you support wheels ? Maybe the cleanest way, in that case we could do the same as triton, expose the part if the python package is present, skip if not ?

This sounds like the best option. 
Packaging our code to be pip-installable is high on my todo list. I'm a little inexperienced in this regard and seems like building wheel for Pytorch CUDA extension is a bit tricky (e.g. maybe CUDA version, Python version, and Pytorch version need to match between the wheel and user's machine?).
Do you guys have more pointers for this issue?

**Comment by blefaudeux** [comment]
> > we just pip install if/when you support wheels ? Maybe the cleanest way, in that case we could do the same as triton, expose the part if the python package is present, skip if not ?
> 
> This sounds like the best option. Packaging our code to be pip-installable is high on my todo list. I'm a little inexperienced in this regard and seems like building wheel for Pytorch CUDA extension is a bit tricky (e.g. maybe CUDA version, Python version, and Pytorch version need to match between the wheel and user's machine?). Do you guys have more pointers for this issue?

to give some context to external onlookers, discussing 1:1 :)

**Comment by danthe3rd** [comment]
Closing as this has been integrated some time ago now :)
We're also working on integrating the newest updates in https://github.com/facebookresearch/xformers/pull/495
