### ISSUE TITLE
Rotary embeddings convert queries and keys to float32 when using mixed precision training

### ISSUE THREAD

**Issue by Tomsen1410** [facebookresearch/xformers#325]
Not sure, if this is expected behaviour. The problem is that the cos_sin table in the RotaryEmbedding class is stored in float32 format, thus the returned queries and keys get converted to float32 aswell.

**Comment by blefaudeux** [comment]
ohh, this is a great catch ! we can fix that, no biggie. Interesting because I'm using these all the time and never remarked that

**Comment by blefaudeux** [comment]
it's also something which would fail in bf16 now that I think about it, worth a fix

**Comment by blefaudeux** [comment]
looks like it was hardcoded to float because a lot of the cos/diag/.. operations are not available with half on CPU. Should be fixed with the attached PR, thanks @Tomsen1410 for the report !
