### ISSUE TITLE
Blocksparse forced to use FP16 when BF16 is supported (for triton v2)

### ISSUE THREAD

**Issue by SeanNaren** [facebookresearch/xformers#353]
# 🐛 Bug

Within the blocksparse implementation,`q,k,v` are forced to half: https://github.com/facebookresearch/xformers/blob/main/xformers/components/attention/blocksparse.py#L171

After #231 I think blocksparse does support bfloat16 (I tried locally and seems it works). If there are no objections, we should modify the constraint to allow bfloat16. Unsure what the correct approach would be (could use the AMP region to infer the type, or the input type).

**Comment by SeanNaren** [comment]
I think we can simplify this further. I suggest using bfloat16 if the type is inferred as bfloat16 (this is pretty much required, as this is the only way you'd get your memory savings) or fallback to float16:

```python
            if q.dtype == torch.bfloat16:
                q, k, v = q.bfloat16(), k.bfloat16(), v.bfloat16()
            else:
                q, k, v = q.half(), k.half(), v.half()
```

**Comment by blefaudeux** [comment]
hey there @SeanNaren, sorry for the huge delay, new job and new life and not too much spare time unfortunately. I think that a core dependency would be to update the triton version that xformers uses to a recent one, I've a branch which started that but a lot of the kernels broke in the meantime (language changes), I'm fixing this but it takes time. After that I agree that blocksparse and everything triton related should use bf16 natively, just a better format than fp16 for ml workloads in general

**Comment by SeanNaren** [comment]
No worries @blefaudeux you and me both :) I've pivoted pretty far from this but would be nice somewhere in time to have this issue resolved!!

**Comment by blefaudeux** [comment]
I finally have a branch up which passes all unit tests with an updated triton @SeanNaren ([triton_update](https://github.com/blefaudeux/xformers/tree/triton_update) on my fork), after that bf16 should be fairly straightforward. II had to change some of the syntax and the dropout layer in particular became very slow, my plan was to fix that (when I get the time, but days I hope), submit it here, and then this one should be an easy follow up that I can do
