### ISSUE TITLE
Release v0.13 with an updated Mem Efficient attention ?

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/xformers#402]
# 🚀 Feature
Make a new 0.13 release with the newer kernels baked in. I can do that if I get a go from the current repo owners (@danthe3rd @fmassa), checking before doing anything wrong

## Motivation
A few people are coming to xformers from the [Stable Diffusion](https://www.reddit.com/r/StableDiffusion/comments/xfu64w/up_to_2x_speed_up_thanks_to_flash_attention/) community, but there are a couple of hurdles on their way. One of them is that `pip install xformers`will not work by default (since it's a release from the beginning of August, and a lot of the enabling work from @danthe3rd is not baked in).

## Pitch
Update the pip package to remove one hurdle on the way

## Alternatives
Well, tell people fo `pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`

## Additional context
https://github.com/huggingface/diffusers/pull/532
It would be great to get some help (from HuggingFace ?) to package wheels, but that's another story :)

**Comment by enn-nafnlaus** [comment]
Same issue as here:

https://github.com/facebookresearch/xformers/issues/497
