### ISSUE TITLE
Question on building xformers

### ISSUE THREAD

**Issue by C43H66N12O12S2** [facebookresearch/xformers#472]
# ❓ Questions and Help
Recently, we merged xformers optimized attention in the AUTOMATIC1111 SD repo ( thanks again for all your help :) ). As Windows wheels are not built by you, I built it myself but it only works on Ampere cards. This forced us to limit the feature to SM8.6 only.

1 - Is there a way to build a single wheel for multi-CUDA capabilities? I tried doing `DEFAULT_ARCHS_LIST = "6.1+PTX;7.5;8.0;8.6"` but this failed with older generations (Pascal, Turing) as well.

2 - If not, what would be your recommendation?

**Comment by yocabon** [comment]
Hi,
In the documentation, it says you should be using TORCH_CUDA_ARCH_LIST : https://github.com/facebookresearch/xformers/blob/main/README.md?plain=1#L78
```
the TORCH_CUDA_ARCH_LIST env variable is set to the architures that you want to support. A suggested setup (slow to build but comprehensive) is export TORCH_CUDA_ARCH_LIST="6.0;6.1;6.2;7.0;7.2;8.0;8.6"
```
6.0;6.1;6.2 would be Pascal
7.0;7.2 is Volta
I suppose 7.5 should be added to the list for Turing support
8.0;8.6 is Ampere

**Comment by fmassa** [comment]
Hi,

Yes, @yocabon is right. You can specify `TORCH_CUDA_ARCH_LIST` to define what are the architectures that you want to build for.

Also, we started adding conda packages for xformers (linux-only for now) in https://anaconda.org/xformers/xformers, so that would be an easier way to get xformers installed

**Comment by C43H66N12O12S2** [comment]
Thank you.
