### ISSUE TITLE
It takes 1 hour 10 minutes to install xFormers on Google Colab... please help

### ISSUE THREAD

**Issue by Yzrsah** [facebookresearch/xformers#481]
# 🚀 Feature

We really wish to use xFormers with Google Colab, but xFormers takes so long to install that we just can't use it.

## Motivation

When using the following method to install xFormers on the Colab:
```
!git clone --depth 1 https://github.com/facebookresearch/xformers.git
%cd xformers
!git submodule update --init --recursive
!pip install -r requirements.txt
!pip install -e .
```

It takes around 1 hour 10 minutes to complete:
```
Installing collected packages: xformers
  Running setup.py develop for xformers
```

## Pitch

Please, any possible way to install xFormers more quickly.

## Alternatives

Is there a binary installation method that would work with Colab?

**Comment by danthe3rd** [comment]
Hi - thanks for reaching out!

This is indeed a pain point of using xformers at the moment, and we are trying to improve the situation. There are a few ways to improve the situation:
(1) Downloading binaries
(2) Making the build process faster
We are working on both fronts.

**(1) Downloading binaries**
Ideally, no one should have to build xformers as it's indeed quite painful and slow. We are working on getting packages out for people to use.
Currently we have packages available for a few versions of pytorch/cuda combinations, but they are only available in `conda`. We are working on making more combinations, and having a way to install them through pip (which is the preferred way of installing packages in Google Collab, cc @bottler )

You can find information about our binary builds on conda here https://github.com/facebookresearch/xformers#installation


**(2) Making the build process faster**
Unfortunately, binaries are not available to everyone. In that case, there are a few things you can do to make the build faster:
(a) Install `ninja` before to parallelise the build (with `!pip install ninja`)
(b) If you know you won't need to use flash attention (that's the case for Stable Diffusion, which uses our own kernels), you can skip building it with the env variable: `XFORMERS_DISABLE_FLASH_ATTN=1`

I hope this helps :)

**Comment by danthe3rd** [comment]
This change might also divide by 2+ the build time by disabling the build of the backward if you don't need it - once it's merged: https://github.com/facebookresearch/xformers/pull/482
