### ISSUE TITLE
error: need cuda arch at least 5.0

### ISSUE THREAD

**Issue by Leonovers** [facebookresearch/xformers#494]
# ❓ Questions and Help
Is it possible to build with cuda arch 3.0?

I have already built PyTorch using the sources, maybe there is a way to build it for arch 3.0?

When building with setup.py it gives error: "Need cuda arch at least 5.0"

**Comment by danthe3rd** [comment]
Hi @Leonovers 

Unfortunately we heavily rely on [CUTLASS](https://github.com/NVIDIA/cutlass) and many features from recent GPUs - this is why we cannot support architectures < 5.0.
