### ISSUE TITLE
Key pad mask support for flash attention

### ISSUE THREAD

**Issue by MathematicalMagus** [facebookresearch/xformers#500]
# ❓ Questions and Help
Hello!
I noticed that FlashAttention [forward](https://github.com/HazyResearch/flash-attention/blob/13403e81157ba37ca525890f2f0f2137edf75311/flash_attn/flash_attention.py#L27) supports the `key_padding_mask` argument, while your implementation allows only for the Causal mask. Can the `key_padding_mask` also (easily) be implemented in xformers?

**Comment by danthe3rd** [comment]
Hi,

Yes it's something we plan on adding. As you mentioned, the kernels already support it, so it's more a matter of figuring out the right API for this - we're looking into pytorch's nested tensors to see if it's the right abstraction

**Comment by danthe3rd** [comment]
We just merged this support - through a special attention bias.
You can learn more on the [doc website](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.fmha.attn_bias.BlockDiagonalMask).
Note that the backward is only supported by Flash, and hence won't work on V100 or older devices or even fp32.
