### ISSUE TITLE
Installation Documentation Problems

### ISSUE THREAD

**Issue by arpowers** [facebookresearch/xformers#512]
Apologies for creating an issue on this but felt it would be useful to address the documentation problems that are making things much harder to work with than needed. 

The installation guide is pretty abstract and most steps are non-linear (A + B, then Skip to F, then back to D)

There are also some missing steps that make things unclear: 

1. How do we actually install xformers in production?
For example, its not clear how to actually INSTALL Xformers! You make it sound like its installed only by compiling a dev build; maybe thats the right way but this should be made clear.

2. This script for the dev build has some problems....
```bash 
git clone git@github.com:facebookresearch/xformers.git 
git submodule update --init --recursive
conda create --name xformer_env python=3.8
conda activate xformer_env
cd xformers
pip install -r requirements.txt
pip install -e .
```
here are problems with this: 
1. git clone with that styles requires auth instead simply: git clone https://github.com/facebookresearch/xformers.git
2. change into xformers dir BEFORE running submodule update 

I know that these simple things might seem like obvious to the devs, but the steps are pretty difficult to follow for those not used to the library.

Thanks for the work, hope this makes it a bit stronger

**Comment by danthe3rd** [comment]
We have done a pass on the documentation to update it with recent changes and make it simpler.
Thanks a lot for the feedback - it really helps, and feel free to reopen if there are other things you think can be improved!
