### ISSUE TITLE
Does this xformers implementation work also with AMD GPUs?

### ISSUE THREAD

**Issue by MatPoliquin** [facebookresearch/xformers#513]
Does xformers work also with AMD GPUs /ROCm or it's implemented specifically for Nvidia cards / CUDA?
If not is there any plans for it?

**Comment by danthe3rd** [comment]
Hi,
xFormers has been developed/tested on Nvidia chips. I don't think it works with ROCm, and we have no plan to support it.
See also this issue: https://github.com/facebookresearch/xformers/issues/485
