### ISSUE TITLE
[Attention] Disable weight scaling

### ISSUE THREAD

**Issue by comaniac** [facebookresearch/xformers#522]
# 🚀 Feature

The current attention implementations scale weights, as shown in the reference implementation (https://github.com/facebookresearch/xformers/blob/main/tests/test_mem_eff_attention.py#L154):

```python
q = q * (1 / q.shape[-1] ** 0.5)
```

However, in some models such as T5, the weight scaling is already applied during weight initialization: https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L803.

As a result, it is not efficient to use memory efficient attention in T5, because we have to either manually change the weight initialization, or revert this scaling before calling the attention op.

## Pitch

Let users configure whether the weight scaling is disabled in attention ops.

**Comment by danthe3rd** [comment]
Hi @comaniac 

That's a good point, and we could indeed add an argument with the scale to apply to `memory_efficient_attention`. I'll add this to my todo list, but I have a few other things to do before.

**Comment by comaniac** [comment]
Thanks for the reply. Will this be tracked by any task tracking issue or roadmap so that I could follow up later? Or if you have a concrete suggestion in mind about how this should be done (e.g., how this should be configured by users), I could probably try to add the support.

**Comment by comaniac** [comment]
Thanks for the details. I'll try to implement it when I got a chance.
