### ISSUE TITLE
Use a newer version of flash attention that compiles faster

### ISSUE THREAD

**Issue by vedantroy** [facebookresearch/xformers#550]
# 🚀 Feature

## Motivation

This package compiles slowly. And I need to build it from source, since I can't use a conda install (I'm using pytorch nightly that I don't think is available on conda).

## Pitch

Use a newer version of flash attention that speeds up compilation: https://github.com/HazyResearch/flash-attention/commit/d95ee1a95da2b138073b5eef0f09ce4de615ba5e

## Alternatives

Not sure.

## Additional context

None

**Comment by danthe3rd** [comment]
Hi @vedantroy and thanks for opening this issue!

Indeed we don't provide builds for pytorch nightly.

This is indeed something we have on our radar (tracking PR: https://github.com/facebookresearch/xformers/pull/495). We have some performance regression issue on the newer version of flash attention (especially for the forward pass), which we want to address before merging, by using @tridao 's implementation in Triton (in PR https://github.com/facebookresearch/xformers/pull/479).
Might take some time to get there, but it's WIP.

On a side-note, we also improved build time for the non-flash attention part in https://github.com/facebookresearch/xformers/pull/539. You should also make sure you have "ninja" installed to use parallelism during the build (should be ~10mn build then)
