### ISSUE TITLE
[Question] Is there a docker container with xformers installed?

### ISSUE THREAD

**Issue by ternaus** [facebookresearch/xformers#577]

**Comment by danthe3rd** [comment]
Hi @ternaus 
Unfortunately, we don't provide docker contains with xformers at the moment. If you are running on Linux, it should just be a matter of:
```bash
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install xformers -c xformers/label/dev
```

**Comment by ternaus** [comment]
I run it with Stable Diffusion, using:

```
    pipe = StableDiffusionPipeline.from_pretrained(model_id, revision="fp16", torch_dtype=torch.float16)
    pipe.scheduler = DPMSolverMultistepScheduler.from_config(pipe.scheduler.config)
    pipe = pipe.to("cuda")

    pipe.unet.to(memory_format=torch.channels_last)  # use channels_last memory format
    pipe.enable_xformers_memory_efficient_attention()
```

Get an error:

```
  File "/home/vladimir/anaconda3/envs/stable_diffusion/lib/python3.9/site-packages/diffusers/models/attention.py", line 309, in set_use_memory_efficient_attention_xformers
    raise e
  File "/home/vladimir/anaconda3/envs/stable_diffusion/lib/python3.9/site-packages/diffusers/models/attention.py", line 303, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "/home/vladimir/anaconda3/envs/stable_diffusion/lib/python3.9/site-packages/xformers/ops/memory_efficient_attention.py", line 967, in memory_efficient_attention
    return op.forward_no_grad(
  File "/home/vladimir/anaconda3/envs/stable_diffusion/lib/python3.9/site-packages/xformers/ops/memory_efficient_attention.py", line 343, in forward_no_grad
    return cls.FORWARD_OPERATOR(
  File "/home/vladimir/anaconda3/envs/stable_diffusion/lib/python3.9/site-packages/xformers/ops/common.py", line 11, in no_such_operator
    raise RuntimeError(
RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
```

**Comment by ternaus** [comment]
But if I use:

```
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```
instead of

```
conda install xformers -c xformers/label/dev
```

xformers.info show:

```
python -m xformers.info
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xFormers 0.0.15.dev+ed99125.d20221212
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.flshattF:               available
memory_efficient_attention.flshattB:               available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        unavailable
memory_efficient_attention.tritonflashattB:        unavailable
swiglu.fused.p.cpp:                                available
is_triton_available:                               False
is_functorch_available:                            False
pytorch.version:                                   1.13.0.post200
pytorch.cuda:                                      available
gpu.compute_capability:                            7.5
gpu.name:                                          NVIDIA GeForce RTX 2080 Ti

```

And I get stack on the error:

```
UDA error (/mnt/samsung960pro/tmp/pip-install-ha6wlutf/xformers_69ae71d995804b0fb442ad4ecb256a92/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:90): no kernel image is available for execution on the device   
```

**Comment by muhammad-ahmed-ghani** [comment]
> But if I use:
> 
> ```shell
> pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
> ```
> 
> instead of
> 
> ```shell
> conda install xformers -c xformers/label/dev
> ```
> 
> `xformers.info` show:
> 
> ```shell
> python -m xformers.info
> A matching Triton is not available, some optimizations will not be enabled.
> Error caught was: No module named 'triton'
> xFormers 0.0.15.dev+ed99125.d20221212
> memory_efficient_attention.cutlassF:               available
> memory_efficient_attention.cutlassB:               available
> memory_efficient_attention.flshattF:               available
> memory_efficient_attention.flshattB:               available
> memory_efficient_attention.smallkF:                available
> memory_efficient_attention.smallkB:                available
> memory_efficient_attention.tritonflashattF:        unavailable
> memory_efficient_attention.tritonflashattB:        unavailable
> swiglu.fused.p.cpp:                                available
> is_triton_available:                               False
> is_functorch_available:                            False
> pytorch.version:                                   1.13.0.post200
> pytorch.cuda:                                      available
> gpu.compute_capability:                            7.5
> gpu.name:                                          NVIDIA GeForce RTX 2080 Ti
> ```
> 
> And I get stack on the error:
> 
> ```
> UDA error (/mnt/samsung960pro/tmp/pip-install-ha6wlutf/xformers_69ae71d995804b0fb442ad4ecb256a92/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:90): no kernel image is available for execution on the device   
> ```

You can try this requirements
```pip install triton==2.0.0.dev20221120 git+https://github.com/facebookresearch/xformers.git@main#egg=xformers```

**Comment by danthe3rd** [comment]
> And I get stack on the error:
> 
> ```
> UDA error (/mnt/samsung960pro/tmp/pip-install-ha6wlutf/xformers_69ae71d995804b0fb442ad4ecb256a92/third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:90): no kernel image is available for execution on the device   
> ```

This should be unrelated to triton. It looks like flash attention was built for a different GPU. Did you install xformers on a machine with a different GPU than the one you are running on now?

**Comment by ternaus** [comment]
Yes, it was on the same GPU.

I finally made it work. 

1. Install pytorch from conda, making sure that Cuda version matches one in Nvidia-smi
`conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia`
2. Install xformers using conda:
`conda install xformers -c xformers/label/dev`

All 

Speed up on inference for Stable Diffusion 2.1 for batch = 15, 2.4 times. 

It is ultra impressive! Thanks!
