### ISSUE TITLE
15h trying to get this to compile/work.

### ISSUE THREAD

**Issue by DarkAlchy** [facebookresearch/xformers#603]
Back in Oct I had no problems compiling this and in about 25m I was done now I am rolling up on 15h straight to no avail.

I finally got it to compile twice in these 15h to end up with this error
![image](https://user-images.githubusercontent.com/10561690/208310331-9f12aacc-c5e1-4ce0-ab6e-d0ebcc812d85.png)

What is wrong?

**Comment by danthe3rd** [comment]
Hi,
The build time didn't increase recently, so I'm not sure why it's taking 15h now. I would recommend that you install one of the (pre-built/binary) [pip wheels](https://github.com/facebookresearch/xformers/issues/533) with:
```bash
pip install --pre -U xformers
```
Would will need to use pytorch 1.13.0 for it to work then.

**Comment by DarkAlchy** [comment]
> Hi, The build time didn't increase recently, so I'm not sure why it's taking 15h now. I would recommend that you install one of the (pre-built/binary) [pip wheels](https://github.com/facebookresearch/xformers/issues/533) with:
> 
> ```shell
> pip install --pre -U xformers
> ```
> 
> Would will need to use pytorch 1.13.0 for it to work then.

Build time had nothing to do with it if you read what I said.  Never did get this thing to compile right as I almost did then got that stupid popup.  15 hours of my life trying to get it to work.
