### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by BroccoliNpikszza** [facebookresearch/xformers#613]
# ❓ Questions and Help
I got this error and I dont know what to do
I tried to install with ven and wthout ven, i also installed latested Cuda 11 and even tried installing with cuda 10 but nothing helped.
HELP PLEASE
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit code 4294967295

**Comment by danthe3rd** [comment]
Hello - can you post more information on your setup? (pytorch version, GPU etc...)
Also how are you installing xformers? Can you include more logs?

We're in the process of getting pip wheels, so I recommend you:
(1) Upgrade pytorch to `1.13.1`
(2) Install xformers with `pip install --pre -U xformers`

**Comment by BroccoliNpikszza** [comment]
Gpu nvidia 1060 cuda 6.1
i used pip install -r requirements.txt pip install -e . to install

**Comment by BroccoliNpikszza** [comment]
But thank u this pip install --pre -U xformers helped

**Comment by BroccoliNpikszza** [comment]
Thanks a lot!!!!!!!!!!!!!!!!!!!!!!

**Comment by danthe3rd** [comment]
Closing then :) Note that if you change your pytorch version, you will have to build xformers from scratch

**Comment by BroccoliNpikszza** [comment]
Okay, thank you!!
