### ISSUE TITLE
Build broken since eaf8c2e90988216e72504b0fcb0f0d4f7020fcb3 on windows

### ISSUE THREAD

**Issue by Aymendje** [facebookresearch/xformers#623]
# 🐛 Bug

Since commit eaf8c2e90988216e72504b0fcb0f0d4f7020fcb3, the build on windows is broken. Pulling the commit just before that works, but anything after it wont work on windows. the CI/CD pipeline is also failing for windows since that commit.

## To Reproduce

See CI/CD pipeline : https://github.com/facebookresearch/xformers/actions/runs/3848806406/jobs/6557047323

**Comment by danthe3rd** [comment]
Just fixed it in https://github.com/facebookresearch/xformers/pull/621
It should work now
