### ISSUE TITLE
"No operator found for this attention" while implementing the _dispath_fw function (in dispatch.py) of  xformers.ops.memory_effiicient_attention

### ISSUE THREAD

**Issue by yukang123** [facebookresearch/xformers#627]
Hi, everyone! I've been using the **xformer** to implement the codes cloned from **stabel diffusion v2** (https://github.com/Stability-AI/stablediffusion).  

I installed the xformer successfully and the stable diffusion code automatically implement attention using xformers library. However, while implementing the xformers.ops.memory_efficient_attention function, the error, "No operator found for this attention", occurred (shown in the below part).

“stablediffusion/ldm/modules/diffusionmodules/model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "/anaconda/envs/ldm-trial/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 193, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/anaconda/envs/ldm-trial/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 289, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/anaconda/envs/ldm-trial/lib/python3.9/site-packages/xformers/ops/fmha/__init__.py", line 305, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/anaconda/envs/ldm-trial/lib/python3.9/site-packages/xformers/ops/fmha/dispatch.py", line 53, in _dispatch_fw
    raise NotImplementedError(f"No operator found for this attention: {inp}")

The command I used to install xformers:
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
conda install xformers -c xformers/label/dev
pip install triton==2.0.0.dev20221120

The info produced by "python -m xformers.info" shows below:
![image](https://user-images.githubusercontent.com/39018085/211279694-ea6cf959-bdb5-47e0-9870-85a6f637b7c1.png)

I would like to know whether somebody else has encountered this issue. And does anyone know the possible reasons of this issue? Is it related to the version of xformers or perhaps the data I used to implement attention?  Thanks a lot!

**Comment by danthe3rd** [comment]
Hi @yukang123 

This means that the combination of inputs is not supported at the moment.
Could you provide:
- the datatypes (we only support f32/bf16/f16)
- the shapes
of the input tensors?
Please note that the input tensors should also be on GPU already

Also, what's the value of `self.attention_op` ? It might be better to leave that to `None` and let xFormers select the best kernel automatically.

**Comment by yukang123** [comment]
Thanks for the timely comment. It seems that I did not put the tensor to the GPU device. Thanks for reminding me this and other information! The issue has been solved. Thanks a lot

**Comment by danthe3rd** [comment]
Yes we need to improve the debugging experience there
