### ISSUE TITLE
Allow custom non-differentiable masks

### ISSUE THREAD

**Issue by AdrienCourtois** [facebookresearch/xformers#645]
# 🚀 Feature

Hello! Currently, the library seems to only support one kind of masking: `xformers.ops.LowerTriangularMask`. Only one attention strategy (`small_k`) supports arbitrary tensors. 
I gather that what makes it hard is the computation of the gradient associated with the mask.
What about allowing users to specify arbitrary masks as long as they can't be backpropagated through?

## Motivation
Some tasks involve masks that are input-specific. Creating this feature could extend the applicability of this library to a more extensive set of tasks.

## Pitch
Allow arbitrary `torch.Tensor` to be passed to the efficient attention strategies without computing the associated gradient.
This would be a first step toward the larger goal of allowing differentiable masks (i.e. positional encoding such as the one used in Swin).

**Comment by danthe3rd** [comment]
Hi @AdrienCourtois 

This is currently supported for the inference only (see https://github.com/facebookresearch/xformers/issues/558).
Support for the backward pass (including with gradient for the bias) is coming with https://github.com/facebookresearch/xformers/pull/587

**Comment by AdrienCourtois** [comment]
Great, thank you so much for the awesome work!
