### ISSUE TITLE
Return old versions to conda

### ISSUE THREAD

**Issue by TsykunovDmitriy** [facebookresearch/xformers#646]
Hi! Thanks for your work. Your package is incredibly useful for research tasks.

I noticed that some builds started disappearing from conda. I worked with this xformers=0.0.15.dev343+git.1b1fd8a=py39_cu11.6_pyt1.13 version and everything was fine. After updating to dev395 I get errors [like this](https://github.com/huggingface/diffusers/issues/1946). Could you bring back previous builds?

Maybe you have the possibility to share the tar.gz archive that we could continue to work on?

**Comment by danthe3rd** [comment]
Hi,
Thanks for opening this issue. Unfortunately, each xFormers build is quite big (~100MB) and we build for multiple combinations of pytorch version/python/CUDA etc... which adds up pretty fast.
Pypi and conda both limit the storage we can use to ~10GB, so we have to remove older builds to be able to upload new ones...
We plan to leave some builds for longer (for stable releases for instance).

You can re-install the version you mention (or any), but you will have to build manually from source. Follow instructions from [there](https://github.com/facebookresearch/xformers#installing-xformers), and replace `main` with the commit hash you want (`1b1fd8a` for you I think). In you case, it should be something like
```bash
# (Optional) Makes the build much faster
pip install ninja
# Set TORCH_CUDA_ARCH_LIST if running and building on different GPU types
pip install -v -U git+https://github.com/facebookresearch/xformers.git@ 1b1fd8a#egg=xformers
# (this can take dozens of minutes)
```

**Comment by TsykunovDmitriy** [comment]
Thanks for the answer. I solved my problem by installing [this version](https://pypi.org/project/xformers/0.0.16rc425/) of xformers and update pytorch version to 1.13.1+cu117.
