### ISSUE TITLE
 Operator `memory_efficient_attention` does not support inputs

### ISSUE THREAD

**Issue by natureXD** [facebookresearch/xformers#669]
# 🐛 Bug

ValueError: Operator `memory_efficient_attention` does not support inputs:
     query       : shape=(32, 256, 1, 160) (torch.float16)
     key         : shape=(32, 256, 1, 160) (torch.float16)
     value       : shape=(32, 256, 1, 160) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 128

![1677207581938](https://user-images.githubusercontent.com/16025234/221081306-5d84efcb-2cd6-42d4-9716-c8a3512076fb.png)

## Environment

![1677207641477](https://user-images.githubusercontent.com/16025234/221081481-f6e51431-a062-4529-8776-039a0d8fba88.png)

- PyTorch Version (e.g., 1.0): 1.13.1+cu117
- OS (e.g., Linux): Window10
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): None
- Python version:  3.10.10
- CUDA/cuDNN version: 117
- GPU models and configuration: 2080，8G
- Any other relevant information:None

## To Reproduce

```python
import torch
from diffusers import StableDiffusionInstructPix2PixPipeline
from xformers.ops import MemoryEfficientAttentionFlashAttentionOp

model_id = "timbrooks/instruct-pix2pix"
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(model_id, torch_dtype=torch.float16, cache_dir="./models/")
pipe = pipe.to("cuda")
pipe.enable_xformers_memory_efficient_attention(attention_op=MemoryEfficientAttentionFlashAttentionOp)
pipe.vae.enable_xformers_memory_efficient_attention(attention_op=None)

url = "https://huggingface.co/datasets/diffusers/diffusers-images-docs/resolve/main/mountain.png"
image = download_image(url)

prompt = "make the mountains snowy"
images = pipe(prompt, image=image, num_inference_steps=20, image_guidance_scale=1.5, guidance_scale=7).images
grid_img = show_images([image, images[0]], 1, 2)
grid_img.save("snowy_mountains.png")
```

**Comment by natureXD** [comment]
The question has been tracked in this [link ](https://codesti.com/issue/huggingface/diffusers/2296) two, but it's also not closed.

**Comment by danthe3rd** [comment]
Hi @natureXD 

Flash-Attention indeed only supports K<=128 - and here K=160. This is supported by the CUTLASS kernel, but it might be significatively slower. You can try it by setting `attention_op=None` (which is the recommended setting anyway):
```
pipe.enable_xformers_memory_efficient_attention(attention_op=None)
```

**Comment by natureXD** [comment]
> K<=128 - and here K=16

Okay, It works with `attention_op=None`. 
Excuse me, could you tell me how to check the effects before and after using the `xformers_memory_efficient_attention`?

**Comment by natureXD** [comment]
> Hi @natureXD
> 
> Flash-Attention indeed only supports K<=128 - and here K=160. This is supported by the CUTLASS kernel, but it might be significatively slower. You can try it by setting `attention_op=None` (which is the recommended setting anyway):
> 
> ```
> pipe.enable_xformers_memory_efficient_attention(attention_op=None)
> ```

@danthe3rd 
Okay, It works with attention_op=None.
Excuse me, could you tell me how to check the effects before and after using the xformers_memory_efficient_attention?

**Comment by danthe3rd** [comment]
> the effects before and after using the xformers_memory_efficient_attention?

I'm not sure I understand - what do you mean?

**Comment by natureXD** [comment]
> This will enable the memory-efficient attention, which should use much less memory. In terms of timing, it might be a little bit slower because you are not in the regime where it is the most efficient. I believe that's something specific to your hardware that you will have to measure.

@danthe3rd 
I suppose that you are still confused with my question.
I want to explain it one more time. 
I want to get the comparison data of using and not using `pipe.enable_xformers_memory_efficient_attention(attention_op=None)`, just like the data as illustrated in this picture：
![image](https://user-images.githubusercontent.com/16025234/221189583-8a97f19c-9168-4fe4-a61d-c5c24a4a9dc7.png)
Could you suggest me some tools or method to get these data？

**Comment by danthe3rd** [comment]
This is the script used to generate these graphs, based on Timm models: https://github.com/facebookresearch/xformers/blob/main/xformers/benchmarks/benchmark_pytorch_transformer.py

If you want to measure time manually, you should make sure you call `torch.cuda.synchronize()` immediately before measuring time. You can also use [torch benchmark utils directly](https://pytorch.org/tutorials/recipes/recipes/benchmark.html)

**Comment by natureXD** [comment]
> This is the script used to generate these graphs, based on Timm models: https://github.com/facebookresearch/xformers/blob/main/xformers/benchmarks/benchmark_pytorch_transformer.py
> 
> If you want to measure time manually, you should make sure you call `torch.cuda.synchronize()` immediately before measuring time. You can also use [torch benchmark utils directly](https://pytorch.org/tutorials/recipes/recipes/benchmark.html)

@danthe3rd Okay, thank you. I appreciate your kind reply to my question so much.
