### ISSUE TITLE
No such operator xformers_flash::flash_fwd

### ISSUE THREAD

**Issue by vedantroy** [facebookresearch/xformers#671]
# ❓ Questions and Help
I'm getting the following error:
```
RuntimeError: No such operator xformers_flash::flash_fwd - did you forget to build xformers with `python setup.py develop`?
```

I built & installed xformers with:
```
            'env FORCE_CUDA=1 XFORMERS_DISABLE_FLASH_ATTN=1 TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5;8.0" pip install -v --no-deps git+https://github.com/facebookresearch/xformers.git@main#egg=xformers'
```

What am I doing wrong?

**Comment by danthe3rd** [comment]
Hi,

You disabled flash-attention at build time, so it wasn't included in your build (`XFORMERS_DISABLE_FLASH_ATTN=1`).
Try removing the `XFORMERS_DISABLE_FLASH_ATTN` part, or set it to 0
