### ISSUE TITLE
How to setup TORCH_CUDA_ARCH_LIST in windows10

### ISSUE THREAD

**Issue by EkaLinjas** [facebookresearch/xformers#672]
# ❓ Questions and Help
![image](https://user-images.githubusercontent.com/125619279/221802577-bec5c350-9d22-40f3-b327-21e029e1433c.png)
My system is windows10 64bit.
I run 'python -m xformers.info' in CMD and it shows  gpu.compute_capability is 8.9 but TORCH_CUDA_ARCH_LIST is not include 8.9.
Is gonna cause bad performence of 4090?
If it is, is anyway to setup TORCH_CUDA_ARCH_LIST to include 8.9? I tried 'set TORCH_CUDA_ARCH_LIST=8.9' in cmd but xformer.info still shows 8.9 is not included in TORCH_CUDA_ARCH_LIST(nothing changed).

**Comment by danthe3rd** [comment]
Hi - `TORCH_CUDA_ARCH_LIST` must be set when building xformers from source, and changes will only be reflected after re-building xformers from source (see ["Install from source"](https://github.com/facebookresearch/xformers#installing-xformers)). The binaries downloaded from pip/conda don't have support for Sm89 at the moment.

> Is gonna cause bad performence of 4090?

I expect this to be not compatible with your 4090 GPU
