### ISSUE TITLE
[Question]How to manually set operator of Memory-efficient attention??

### ISSUE THREAD

**Issue by ima9ine** [facebookresearch/xformers#673]
# ❓ Questions and Help

Hi I'm new to xformers and try to use memory-efficient attention.

[xformer doc](https://facebookresearch.github.io/xformers/components/ops.html) say set "op" to use among  [xformers.ops.AttentionOpBase](https://facebookresearch.github.io/xformers/components/ops.html#xformers.ops.AttentionOpBase). 

but I don't know how to correctly set op argument.

what i did is below

```python
from xformers.ops.fmha.flash import FwOp 
xops.memory_efficient_attention(q,k,v, op=FwOp)
```

**Comment by danthe3rd** [comment]
Hi @ima9ine 
We recommend leaving `op=None` to let xFormers chose the best kernel based on heuristics - it's also the default value if you don't specify it

I hope this helps

**Comment by fmassa** [comment]
Closing following @danthe3rd answer
