### ISSUE TITLE
Force xops to use not-flash based attention.

### ISSUE THREAD

**Issue by vedantroy** [facebookresearch/xformers#674]
# ❓ Questions and Help
Is there a way to force xformers to not use flash-based attention?
Specifically, when calling `memory_efficient_attention`, I'd like xformers to *not* use flash attention, even if the GPU supports it, and instead use the older variant.

**Comment by danthe3rd** [comment]
Hi,

You can do that by specifying the `op` argument.
If you want to use the CUTLASS kernel, you can use:
```python
from xformers.ops import fmha

op = (fmha.cutlass.FwOp, fmha.cutlass.BwOp)
```

Out of curiosity, why is Flash not working for you?

**Comment by vedantroy** [comment]
> Hi,
> 
> You can do that by specifying the `op` argument. If you want to use the CUTLASS kernel, you can use:
> 
> ```python
> from xformers.ops import fmha
> 
> op = (fmha.cutlass.FwOp, fmha.cutlass.BwOp)
> ```
> 
> Out of curiosity, why is Flash not working for you?

Flash is working fine for me, I just want to run some tests.

Specifically, I know on V100's xformers is not using flash attention.
And, presumably on A100's xformers is using flash attention.

So I'm trying to write some tests, where
- test 1 is using vanilla attention
- test 2 is using flash attention
- test 3 is using efficient attention (but not flash)

And I would like to then compare the numerical error, etc.
Do you know which ops correspond to test1/test/test3 respectively?

**Comment by danthe3rd** [comment]
test 1 is not implemented within `memory_efficient_attention`, as it's not memory efficient
For the others:

```python
from xformers.ops import fmha

test2_op = (fmha.flash.FwOp, fmha.flash.BwOp) # This will fail if running on V100
test3_op = (fmha.cutlass.FwOp, fmha.cutlass.BwOp)
```

**Comment by danthe3rd** [comment]
note that we also have a triton-based operator - requires V100+ and a [specific version](https://github.com/facebookresearch/xformers/blob/main/requirements-test.txt#L31) of triton
```python
triton_op = (fmha.triton.FwOp, fmha.triton.BwOp)
```

**Comment by vedantroy** [comment]
> note that we also have a triton-based operator - requires V100+ and a [specific version](https://github.com/facebookresearch/xformers/blob/main/requirements-test.txt#L31) of triton
> 
> ```python
> triton_op = (fmha.triton.FwOp, fmha.triton.BwOp)
> ```

Thanks for the information, will `scaled_dot_product_attention` run vanilla attention?

**Comment by vedantroy** [comment]
And final question, I'm assuming that the numerical difference between the different variants of efficient attention are small enough that--let's say on an A100 xformers uses the flash kernel--but then I run inference on a V100, where xformers uses the cutlass kernel, this will not meaningfully affect results, right?

**Comment by danthe3rd** [comment]
For the vanilla attention, you can use the implementation we have on the test for memory_efficient_attention:
https://github.com/facebookresearch/xformers/blob/57edbb7a7e313b8c8d3b6e2b67b201b877b9d78b/tests/test_mem_eff_attention.py#L190-L240

I believe that `scaled_dot_product_attention` takes inputs in a slightly different format (BMK only, whereas you might have inputs in BMHK format, where B=batch size, M=seqlen, H=num heads, K=embed per head)



> I'm assuming that the numerical difference between the different variants of efficient attention are small enough that--let's say on an A100 xformers uses the flash kernel--but then I run inference on a V100, where xformers uses the cutlass kernel, this will not meaningfully affect results, right?

I believe it shouldn't affect results, as the algorithms are very similar

**Comment by vedantroy** [comment]
> For the vanilla attention, you can use the implementation we have on the test for memory_efficient_attention:
> 
> https://github.com/facebookresearch/xformers/blob/57edbb7a7e313b8c8d3b6e2b67b201b877b9d78b/tests/test_mem_eff_attention.py#L190-L240
> 
> I believe that `scaled_dot_product_attention` takes inputs in a slightly different format (BMK only, whereas you might have inputs in BMHK format, where B=batch size, M=seqlen, H=num heads, K=embed per head)
> 
> > I'm assuming that the numerical difference between the different variants of efficient attention are small enough that--let's say on an A100 xformers uses the flash kernel--but then I run inference on a V100, where xformers uses the cutlass kernel, this will not meaningfully affect results, right?
> 
> I believe it shouldn't affect results, as the algorithms are very similar

Got it. Thanks.

When comparing, the output of
- The xformer's cutlass kernel
- Tri Dao's original flash attention code
- Vanilla attention, using an attention implementation taken from the flash attention repository.

I got the following results:

```
xformer_output vs normal_output
         Abs: 47.5
         Mean: -0.006214141845703125
         Median: 0.0
flash_output vs normal_output
         Abs: 47.5
         Mean: -0.006214141845703125
         Median: 0.0
```

I'm not sure if this is normal, `47.5` seems a little high--but I have no idea, maybe this is expected in terms of numerical error.

Interestingly enough, the cutlass kernel & the flash attention kernel from Tri Dao's repository both give the exact same results, which is nice since it means training on a V100 vs an A100 shouldn't make a difference.
