### ISSUE TITLE
Is it torch1.11 supported?

### ISSUE THREAD

**Issue by wikiwen** [facebookresearch/xformers#695]
# ❓ Questions and Help
I see "torch >= 1.12" in requirements.txt. But Is it torch1.11 supported, which is not a very old version.
If not supported, how can i change some code to support it?

**Comment by danthe3rd** [comment]
Hi,
I'm not sure why we have this requirement. You can try to remove it and build from source. It might work, but that's not something we will officially support.
Out of curiosity, why can't you use PyTorch 1.12.1 or newer?

**Comment by wikiwen** [comment]
> 
Thanks for your reply. I will try it. I use torch1.11 because many machine has old nvidia driver. If use new torch. need update nvidia driver or re-compile torch.
