### ISSUE TITLE
ONNX

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/xformers#699]
# ❓ Questions and Help
Hi 👋 

I hope the question is not to stupid but what happens if I export a model with efficient attention to ONNX, will I still get the same benefits?

Thanks a lot

Fra

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @fmassa , thanks a lot :)

**Comment by pfeatherstone** [comment]
Is there a way for this library to fallback to dummy implementations which can be exported to ONNX?
