### ISSUE TITLE
Installing xformes from direct link to version 0.14 installs version 0.16

### ISSUE THREAD

**Issue by kgonia** [facebookresearch/xformers#704]
# 🐛 Bug

Installing xformes from direct link to version 0.14 installs version 0.16

## To Reproduce

I run this command

`pip install -U -I --no-deps --upgrade --force-reinstall https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/linux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl`

and I got this output 

```
Collecting xformers==0.0.14.dev0
  Downloading https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/linux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl (108.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.4/108.4 MB 8.1 MB/s eta 0:00:00
Installing collected packages: xformers
Successfully installed xformers-0.0.16
```

It looks like after instalation there is version mismatch.

## Environment

PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: glibc-2.31

Python version: 3.10.10 (main, Mar 27 2023, 12:30:09) [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-1026-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.6
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-lightning==1.9.0
[pip3] torch==1.13.1+cu117
[pip3] torchaudio==0.13.1+cu117
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.14.1+cu117
[conda] No relevant packages

**Comment by danthe3rd** [comment]
Hi,
We recommend that you follow the instructions in our README to install xFormers. The wheel you downloaded (from `https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/linux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl`) is not an official build of xFormers, and we can't help you with that.
Out of curiosity, is there any reason why you want version `0.0.14` and not a more recent one?

**Comment by kgonia** [comment]
> Out of curiosity, is there any reason why you want version `0.0.14` and not a more recent one?

@danthe3rd 
Correct me if I'm wrong but certain version of xformers works only with certain version of pythorch and I setup enviroment for project with older pytorch.

Anyway, without solving this particular issue, I managed to solve it by using newer pytorch and newer xformers.
