### ISSUE TITLE
For what  possible reasons you could remove older xformers versions?

### ISSUE THREAD

**Issue by FurkanGozukara** [facebookresearch/xformers#708]
We were using xformers 0.0.17dev476 version very well with torch version 1 and cuda 11.7

Now you removed it and we have to use torch 2

However torch 2 is not working on unix runpod

Therefore we are not able to use runpod as we wanted as before

I cant find any radical explanation of removing all versions

So how can I obtain older versions?

Such as 0.0.17dev476

how can I compile it on unix machine? 

Here my torch 2 problem on runpod unix

i am trying to run dreambooth on runpod

unfortunately pytorch team removed xformers older version

now we have to use torch 2
however it is not working on runpod

here the errors and steps i tried to solve the problem

I have installed Torch 2 via this command on RunPod io instance

`    pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Everything installed perfectly fine

With Torch 1 and Cuda 11.7, I was not getting any error but with Torch 2 the below error produced 

   ` Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory`

How to fix?

It is using unix

On Windows same prodecure working very well

Using Automatic1111 web UI to use Stable Diffusion

this above i couldnt solve

therefore i have done the following things

apt update
apt install sudo
sudo apt install nvidia-cudnn
sudo apt-get install python3-dev

after installing all above

now i have this warning and training never progress

`Steps:   0%|                                                  | 0/170 [00:00<?, ?it/s][2023-03-29 18:50:26,163] torch._inductor.utils: [WARNING] not enough cuda cores to use max_autotune mode`

now when i run below python code i see everything looking good

```
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    print("CUDA is available")
    # Display the current GPU name
    print("GPU name: ", torch.cuda.get_device_name(torch.cuda.current_device()))
else:
    print("CUDA is not available")

# Verify the PyTorch version
print("PyTorch version: ", torch.__version__)

import torch
print(torch.cuda.get_device_properties(0).multi_processor_count)
```

test.py result

```
CUDA is available
GPU name:  NVIDIA RTX A4500
PyTorch version:  2.0.0+cu118
56

```

it is able to generate images with 15.58it which is very fast

any help appreciated very much

**Comment by danthe3rd** [comment]
Hi, 
We are limited by pypi/conda by the number of builds we can keep. Furthermore, on pypi we can only have a single Pytorch version per xFormers version. That's why we don't keep binaries for ever.
However, we have the latest version of XFormers for PT 1.12.1, 1.13.1 and 2.0.0 on anaconda that you can use

**Comment by FurkanGozukara** [comment]
> Hi, We are limited by pypi/conda by the number of builds we can keep. Furthermore, on pypi we can only have a single Pytorch version per xFormers version. That's why we don't keep binaries for ever. However, we have the latest version of XFormers for PT 1.12.1, 1.13.1 and 2.0.0 on anaconda that you can use

Hello. We can't use those. Torch 1.13.1 works with xformers 0.0.17 dev version for stable diffusion training and you removed all those versions

What kind of decision is this?

You even removed 0.0.14

Can you upload somewhere else we can manually install?

**Comment by danthe3rd** [comment]
Version `0.0.16` works with PyTorch 1.13.1 and is still available on pip (https://pypi.org/project/xformers/0.0.16/).
Version `0.0.17` is also compatible with PyTorch 1.13.1 if you install it with conda within a conda environment (linux only):
```bash
conda install xformers -c xformers pytorch=1.13.1 torchvision torchaudio -c pytorch
```

**Comment by FurkanGozukara** [comment]
> Version `0.0.16` works with PyTorch 1.13.1 and is still available on pip (https://pypi.org/project/xformers/0.0.16/). Version `0.0.17` is also compatible with PyTorch 1.13.1 if you install it with conda within a conda environment (linux only):
> 
> ```shell
> conda install xformers -c xformers pytorch=1.13.1 torchvision torchaudio -c pytorch
> ```

0.0.16 is not compatible with stable diffusion training. You can remove that and add 0.0.17 please?

**Comment by ArrowM** [comment]
> Hi, We are limited by pypi/conda by the number of builds we can keep. Furthermore, on pypi we can only have a single Pytorch version per xFormers version. That's why we don't keep binaries for ever. However, we have the latest version of XFormers for PT 1.12.1, 1.13.1 and 2.0.0 on anaconda that you can use

Ahh, thank you for the explanation.

**Comment by danthe3rd** [comment]
Also, as it might help: our CI is still building wheels for previous versions of pytorch (like 1.13.1), but we just don't upload them to pypi due to only being able to have a single pytorch version per pypi version.
However you can download them manually and install them. Just click on the CI check on a commit, and select the wheel build you want
![image](https://user-images.githubusercontent.com/43445237/228680589-e6ca81d0-e0ae-4048-9b0f-c3abb808f2e1.png)
In the job summary, you can download the specific version for your OS/python version/pytorch version, for example here:
https://github.com/facebookresearch/xformers/actions/runs/4545653740

**Comment by FurkanGozukara** [comment]
> Also, as it might help: our CI is still building wheels for previous versions of pytorch (like 1.13.1), but we just don't upload them to pypi due to only being able to have a single pytorch version per pypi version. However you can download them manually and install them. Just click on the CI check on a commit, and select the wheel build you want ![image](https://user-images.githubusercontent.com/43445237/228680589-e6ca81d0-e0ae-4048-9b0f-c3abb808f2e1.png) In the job summary, you can download the specific version for your OS/python version/pytorch version, for example here: https://github.com/facebookresearch/xformers/actions/runs/4545653740

hello again

i have downloaded `ubuntu-22.04-py3.9-torch1.13.1+cu117.zip`

uploaded here 

`https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/xformers-0.0.18.dev489-cp39-cp39-manylinux2014_x86_64.whl`

then i tested to install as

`pip install https://huggingface.co/MonsterMMORPG/SECourses/resolve/main/xformers-0.0.18.dev489-cp39-cp39-manylinux2014_x86_64.whl`

however I am getting this error any ideas?

`ERROR: xformers-0.0.18.dev489-cp39-cp39-manylinux2014_x86_64.whl is not a supported wheel on this platform.`

**Comment by FurkanGozukara** [comment]
@danthe3rd thank you so much for your help

with your help i made it work and prepared the tutorial

18.) RunPod - Automatic1111 Web UI - Cloud - Paid - No PC Is Required
[RunPod Fix For DreamBooth & xFormers - How To Use Automatic1111 Web UI Stable Diffusion on RunPod](https://www.youtube.com/watch?v=zA4LksIVas8) 
[
![image](https://user-images.githubusercontent.com/19240467/228829128-e32d2900-0162-4de7-ba78-887b9083b090.png)
](https://www.youtube.com/watch?v=zA4LksIVas8)
