### ISSUE TITLE
[perf] merging computation across triton kernels

### ISSUE THREAD

**Issue by ClashLuke** [facebookresearch/xformers#71]
Is it possible to reasonably merge our matmul, activation, normalization, attention and soon-to-be-added GLU kernels into one large kernel without writing a fused kernel?</br>
If we're able to do that, I propose adding triton kernels for RevNet so that we can compile the entire model instead of just parts of it. Unless anyone else wants to, I could work on implementing that.

**Comment by blefaudeux** [comment]
Closing that @ClashLuke, let me know if I misunderstood and you would like something done along these lines

**Comment by moinnadeem** [comment]
@ClashLuke @blefaudeux Out of curiosity, is the GLU kernels added into dev? I can't find them on the documentation or `xformers.triton` folder. I would definitely be a user of them if we had them!
