### ISSUE TITLE
Using memory_efficient_attention with xFormer.from_config?

### ISSUE THREAD

**Issue by lendle** [facebookresearch/xformers#721]
# ❓ Questions and Help

Is it possible to use `memory_efficient_attention` with xFormer.from_config? I understand I can use different [attention mechanisms](https://facebookresearch.github.io/xformers/components/attentions.html) via configuration, but I don't see a way to specify using `memory_efficient_attention` with model_factory or block_factory. 

I think the answer is no, but wanted to confirm.

**Comment by danthe3rd** [comment]
Hi,
Indeed the answer is no. We know it's not a satisfactory answer, but for now using mem-eff requires you to have your own transformer architecture written in Python.
Out of curiosity, could you specify why you are using the factory, and what special settings you use if any?

**Comment by lendle** [comment]
I'm just experimenting with different attention implementations right now. So far only with tutorials. I wanted to try comparing memory usage and throughput for standard ScaledDotProduct vs memory efficient and using the model factory seemed like a quick way to play with it if it was possible.
