### ISSUE TITLE
error when install from the source

### ISSUE THREAD

**Issue by leoxxxxxD** [facebookresearch/xformers#735]
# ❓ Questions and Help
Hi, I was trying to build from source, and when I ran pip install -e., I got the following outputs, could you help to have a look please?
Traceback (most recent call last):
  File "setup.py", line 289, in <module>
    from xformers.version import __version__
ModuleNotFoundError: No module named 'xformers.version'

**Comment by xw0629** [comment]
https://github.com/facebookresearch/xformers/tree/7e05e2caaaf8060c1c6baadc2b04db02d5458a94
my server is not networked, so I can only compile and install offline, this is my system environment: torch1.12, cuda11.3, can you tell me how to install, thx

**Comment by danthe3rd** [comment]
Can you try with a more recent version of xFormers? Like main latest if possible

**Comment by garychan22** [comment]
@leoxxxxxD hi, how did you resolve this problem? share some solutions?

**Comment by WuXiaoxuan99** [comment]
I'm stuck with the same problem, did you solve it? Can you share some ideas for solving it?
