### ISSUE TITLE
Install xformers failed, clang: error: unsupported option '-fopenmp'

### ISSUE THREAD

**Issue by yellowfish82** [facebookresearch/xformers#738]
# 🐛 Bug

I tried to install xformers on my mac but get an error

clang and clang++ version is here
<img width="392" alt="image" src="https://user-images.githubusercontent.com/49299570/235700825-9a7dc9f9-e0c8-4a1f-b7e3-8a81b6c92fab.png">

I already installed llvm and libomp by brew

I think the key error message is:
**clang: error: unsupported option '-fopenmp'**

the following is the error details:
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235701621-cd35e6f8-9630-43c4-aa32-a9fce947e045.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235701938-76b9eebc-0403-4c9f-a446-c7916e797bf9.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702021-9fc9b4b6-8f8e-46c1-addf-04470b95d356.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702066-ffca1945-b0ea-4bff-83db-be469e13a1fe.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702128-652f6c41-3d93-4bd9-8718-2671d5b48a2b.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702227-7ff1cd50-5760-4b49-a1ac-774594404ba6.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702294-f56cc072-8d13-4800-9cb4-a421efca98d9.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702375-fa657fc4-80cc-4424-a8cf-061930528e09.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/49299570/235702435-fa8e3a96-1069-4604-8a0e-e29485805eeb.png">

## Command
pip install xformers

## To Reproduce
my python version is 3.10.9
my pip version is 23.1.2
my torch version is 2.0.0
I am using the vrituralenv and its version is 20.21.0
I also using conda its version is 23.1.10

I tried either using conda or without it which has the same error

## Expected behavior
Expect xformers installed successfully.

## Environment

the following is my mac information
<img width="547" alt="image" src="https://user-images.githubusercontent.com/49299570/235698978-51fa9b3e-f97d-4060-84b4-b14fa4550539.png">

**Comment by danthe3rd** [comment]
Hi,
xFormers does not support MacOS, as it's not supported by CUDA

**Comment by yellowfish82** [comment]
thx!
