### ISSUE TITLE
document of memory_efficient_attention is wrong

### ISSUE THREAD

**Issue by Sleepychord** [facebookresearch/xformers#761]

**Comment by danthe3rd** [comment]
Thanks for reporting! This is indeed correct, the "equivalent pytorch code" assumes a single head.
Converting from BMHD -> BHMD takes a few lines of code and would make the code less readable I believe.
I'm happy to accept contributions to make this better

**Comment by Sleepychord** [comment]
Thank you for your response. I know your meaning but if someone (like me) use the "equivalent code" to verify the results, it will take a long time to figure out why.  By the way, the comments also says
```
:parameter attn_bias: Bias to apply to the attention matrix - defaults to no masking. \
        For common biases implemented efficiently in xFormers, see :attr:`xformers.ops.fmha.attn_bias.AttentionBias`. \
        This can also be a :attr:`torch.Tensor` for an arbitrary mask (slower).
``` 
however, I encounter a error "`flshattF` is not supported because: attn_bias type is <class 'torch.Tensor'>". Seems like this description is also not right.

**Comment by danthe3rd** [comment]
> however, I encounter a error "`flshattF` is not supported because: attn_bias type is <class 'torch.Tensor'>". Seems like this description is also not right.

We have multiple backends to run memory efficient attention. Flash Attention is one of them - and it does not support tensor bias indeed.
We recommend that you don't request a backend explicitly (eg don't specify `op` argument) - so that xformers will automatically select the best performing one among the compatible ones.

**Comment by Sleepychord** [comment]
Yes, but seems like none of the backend support attn_bias if k is larger

**Comment by danthe3rd** [comment]
What version of xformers are you using? Can you copy-paste the code you use to call `memory_efficient_attention`, along with the complete error message you get?
