### ISSUE TITLE
mha bwd performance

### ISSUE THREAD

**Issue by lgfun** [facebookresearch/xformers#774]
Hi dear @danthe3rd :

I test the performance of xformer's mha backward using (BMHK=1,2048,14,128，dtype bfloat16, A100 GPU), and the backward kernel time was about 9ms，meanwhile, I use torch writing the same backward layer, and torch mha  backward average use about 0.9ms, the gap is a little big.

In my case, xformer's mha only launch B x N(1 x 14 = 14) blocks, while A100 has 108 SMs, so the efficiency is not good enough, and I found each block has two for loops in it to calculate the final GradQKV, when sequence length grows, the loops will increase significantly.

How can I use more blocks to calc the backward, and decrease the nested for loops? In my view, the forward implementation of mha is good enough cause many blocks will launch around sequence length axis, why backward not follow it?

Best regards :)

**Comment by danthe3rd** [comment]
Hi @lgfun 
That's a very good point - and great investigation! However this is something that we have fixed recently in https://github.com/facebookresearch/xformers/commit/19902ae0a4a60a484a4938cb0c4fa762e339fe84 (we have improved the parallelization), and should be available starting in [xFormers 0.0.20](https://github.com/facebookresearch/xformers/blob/main/CHANGELOG.md#0020---2023-05-23).
Can you make sure you are using version 0.0.20 or newer? Also note that this will be *disabled* if you are running in deterministic mode

**Comment by lgfun** [comment]
> 

thanks a lot!
