### ISSUE TITLE
bias_4d_view.stride(0) overflows When using memory_efficient_attention

### ISSUE THREAD

**Issue by JUGGHM** [facebookresearch/xformers#788]
# 🐛 Bug

## To Reproduce

from xformers.ops import memory_efficient_attention
....
memory_efficient_attention(q, k, v, attn_bias=attn_bias[:, :, :N])

q.shape [2, 12180, 16, 64]  (also for k and v )
attn_bias.shape [32, 12180, 12184]

## Expected behavior

  File "~/mu.hu/.conda/envs/new/lib/python3.9/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: bias_4d_view.stride(0) overflows

## Environment

- PyTorch Version (2.0.1):
- OS (Linux):
- How you installed PyTorch (pip):
- Python version: 3.9
- CUDA/cuDNN version: 11.3
- GPU models and configuration: A100

**Comment by JUGGHM** [comment]
I would like to adapt a sliding-window strategy for standard vits, so I generate an attn_bias by myself. When the input image becomes larger, however, the attn_bias matrix gets over-flowing. Are there any more elegant solutions utilizing the off-the-shelf attn-bias classes?

**Comment by JUGGHM** [comment]
OK, I find ScaleDotProduct a usable alternative

**Comment by JUGGHM** [comment]
> OK, I find ScaleDotProduct a usable alternative

But this class does not support multi-head attention, do we have a expected one here?

**Comment by danthe3rd** [comment]
Please update to the latest xFormers (nightly) for a fix to this with 
```
pip install --pre -U xformers
```

**Comment by JUGGHM** [comment]
> pip install --pre -U xformers

Thank you for your answer. But I still get the same error reported with a latest version of xformers 0.0.21.dev564. Is it possible that the length of sequence is too long and the attention bias matrix is too large?

**Comment by danthe3rd** [comment]
Yes this was the issue, but it should be fixed in https://github.com/facebookresearch/xformers/commit/471569b4c8adec77ba79023cfa9e9f5598284542 which is included in the `dev564` version you have ...
Can you create a minimal reproducible example, along with how you create the Q/K/V/attn_bias tensors (eg `torch.randn([size...])`)

**Comment by JUGGHM** [comment]
> 

Thank you danthe!! Everything is working fine now!!!!!!!!!!!

**Comment by ShadowTeamCN** [comment]
> Please update to the latest xFormers (nightly) for a fix to this with
> 
> ```
> pip install --pre -U xformers
> ```

not solved for me , i have the same issue
