### ISSUE TITLE
speed vs flash

### ISSUE THREAD

**Issue by DachengLi1** [facebookresearch/xformers#791]
Hi team thanks for the great work. I have two questions:
(1) If A100, Xformer will use flash attention?
(2) Use the same GPU, will xformer be slower than flash attn since it does not minimize HBM access?

Thanks!

**Comment by danthe3rd** [comment]
Hello, on A100, xFormers will use either Flash or the CUTLASS implementation we have, as both are available [1]. We will select the fastest implementation available depending on your problem size.

> Use the same GPU, will xformer be slower than flash attn since it does not minimize HBM access?

xformers also minimizes HBM access, similar to Flash-Attention


[1] Assuming you are in either bf16/f16 and don't have an attention bias (beside causal)

**Comment by fxmarty** [comment]
Hi @danthe3rd , following this commit https://github.com/facebookresearch/xformers/commit/cfea89fab5e42a99f961d445ac2b06d4b43126ce#diff-6ffc547e102d4e367e017498c0697c9be0b1901c9f940fef64a2a5c49b613c0b that always returns False for `_is_cutlass_fwd_faster_than_flash` & `_is_triton_fwd_fastest`, it appears that xformers now always prioritize flash attention (except for the forward-only, non MQA case, that seem to prioritize `efficient_attention_forward_decoder` in a few cases). Is that correct?

**Comment by danthe3rd** [comment]
Yes that is correct. This is since Flashv2 which is now faster than the xFormers reimplemention across all problem sizes. We still use our reimplemention when flash is not available (V100, f32, with bias etc ...)
