### ISSUE TITLE
install xformers alway re-install torch with cuda-11.7

### ISSUE THREAD

**Issue by ShomyLiu** [facebookresearch/xformers#802]
# ❓ Questions and Help
Hi,  when I use pip install xformers, it will re-install the torch==2.0.1 with cuda-11.x, even if I have the torch=2.1.0 with cuda 12.1 in nvcr.io/nvidia/pytorch:23.06-py3.  Does it support the latest cuda and torch?

Thanks.

**Comment by danthe3rd** [comment]
Yes and yes, but you will have to [build from source](https://github.com/facebookresearch/xformers/tree/main#installing-xformers)

**Comment by ShomyLiu** [comment]
Thanks for your reply, I will try to re-build
