### ISSUE TITLE
Rebuild latest wheels on main for FlashAttention 2

### ISSUE THREAD

**Issue by winglian** [facebookresearch/xformers#805]
# 🐛 Bug

This bug https://github.com/Dao-AILab/flash-attention/issues/338 in FlashAttention 2 was only fixed more recently than the last change that added FlashAttention 2. The fix is here https://github.com/Dao-AILab/flash-attention/commit/9ee0ff1d9b6a99630e2a6868b9291dfa32d35abd. Rebuilding the wheels on main should fix this for xformers too.

**Comment by danthe3rd** [comment]
Hi,
Thanks for opening this issue! Happy to accept a PR to update the submodule.
Otherwise I'll do it later today.

**Comment by peterjc123** [comment]
@danthe3rd Any plan to upload the latest wheels to PyPI with flash attention v2?

**Comment by tmm1** [comment]
Note that flash-attn 2.0.4 was released with additional bug fixes. The submodule should be bumped again.
