### ISSUE TITLE
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by alecgalingit** [facebookresearch/xformers#817]
When I try to install xformers on my mac, I'm getting the following error: "ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects".

**Comment by laurasilvanavi** [comment]
@alecgalingit I see you closed the issue, how did you manage to solve it? I'm still getting the same

**Comment by eryk-mazus** [comment]
same

**Comment by Dawn-LX** [comment]
same error, I want to build xformer with torch.2.0.0, so I build it from the source as 

```
# (Optional) Makes the build much faster
pip install ninja
# Set TORCH_CUDA_ARCH_LIST if running and building on different GPU types
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
# (this can take dozens of minutes)
```

and this error occurs:
```
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects
```
