### ISSUE TITLE
How can I get the Attentionmaps when calculating the attention?

### ISSUE THREAD

**Issue by mtjmtj** [facebookresearch/xformers#821]
I wonder how can I get the Attentionmaps when calculating the attention using the code below:
**hidden_states = xformers.ops.memory_efficient_attention(query, key, value, attn_bias=attention_mask)**

**Comment by danthe3rd** [comment]
Hi,
We don't support returning the attention maps in this API - most of the speedup is precisely because we don't write these attention maps to memory.
