### ISSUE TITLE
binary whl for PyTorch 2.1.0 RC1

### ISSUE THREAD

**Issue by daxijiu** [facebookresearch/xformers#835]
PyTorch 2.1.0 RC1 version is out, perhaps a 0.0.22 dev version of the binary whl file can be released to support it for easy testing? (After all, compiling it on one's own is not particularly convenient.)

https://download.pytorch.org/whl/test/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl
https://download.pytorch.org/whl/test/cu121/torch-2.1.0%2Bcu121-cp310-cp310-win_amd64.whl

**Comment by danthe3rd** [comment]
Hi,
We don't plan to support wheels for RC versions at this point. We will add support once the final 2.1.0 is out

**Comment by daxijiu** [comment]
ok got it
