### ISSUE TITLE
migration to cutlass 3.x

### ISSUE THREAD

**Issue by GuanhuaWang** [facebookresearch/xformers#849]
Just wondering if there is a recent plan on migrating from cutlass 2.x to 3.x?

**Comment by danthe3rd** [comment]
Hi,
Yes we plan to migrate soon to CUTLASS 3, as it should mostly be compatible.

**Comment by yiyangh-ps** [comment]
Do we have a more refined expectation of the date of the release? Even a alpha version will do.

**Comment by danthe3rd** [comment]
Hi,
I'll try to do that next week

**Comment by yiyangh-ps** [comment]
@danthe3rd this might be relavent: https://github.com/NVIDIA/cutlass/issues/1094

**Comment by danthe3rd** [comment]
@yiyangh-ps  oh that's a good point that might be blocking the migration actually ...

**Comment by danthe3rd** [comment]
We just updated to CUTLASS 3.2 in https://github.com/facebookresearch/xformers/commit/af6b866f1b1340f2b4681d1ad1c5fe96957307a9
