### ISSUE TITLE
Singleton batch dimension `attn_bias` support for `memory_efficient_attention`

### ISSUE THREAD

**Issue by leonfedden** [facebookresearch/xformers#854]
# ❓ Questions and Help
I am wondering if it's possible to pass in a singleton batch dimension attention bias to `memory_efficient_attention`. For example, for my model I have such a bias with shape `torch.Size([1, 3, 512, 512])` but the operation requires me to match the k,q,v batch dimension of `864`.

```py
ipdb> xops.memory_efficient_attention( 
    query=q.permute(0, 2, 1, 3).to(to_dtype), 
    key=k.permute(0, 2, 1, 3).to(to_dtype), 
    value=v.permute(0, 2, 1, 3).to(to_dtype),  
    attn_bias=attn_bias.to(to_dtype),
    p=attn_drop_p, 
    scale=scale,  
    op=(op_module.FwOp, op_module.BwOp),
)
*** ValueError: Invalid shape for attention bias: torch.Size([1, 3, 512, 512]) (expected (864, 3, 512, 512))
  query.shape: torch.Size([864, 512, 3, 16])
  key.shape  : torch.Size([864, 512, 3, 16])
  value.shape: torch.Size([864, 512, 3, 16])
```

Any guidance deeply appreciated. I tried to look at a custom AttentionBias object, but I'm not sure if that's the right way to go - I can't find much in the way of how that's used and I suspect this might need be supported at the custom kernel level. I'd love to hear an expert's opinion on this! 

Many thanks in advance :)

**Comment by danthe3rd** [comment]
Hi,
You can `expand` your attention bias with something like:
```python
xops.memory_efficient_attention( 
    query=q.permute(0, 2, 1, 3).to(to_dtype), 
    key=k.permute(0, 2, 1, 3).to(to_dtype), 
    value=v.permute(0, 2, 1, 3).to(to_dtype),  
    attn_bias=attn_bias.to(to_dtype).expand(v.shape[0], -1, -1, -1),
    p=attn_drop_p, 
    scale=scale,  
    op=(op_module.FwOp, op_module.BwOp),
)
```

**Comment by leonfedden** [comment]
Oh brilliant, that'll make a view rather than a memory allocation. Should have realised, thanks so much @danthe3rd !
