### ISSUE TITLE
Expected batchsize when using BlockDiagonalMask

### ISSUE THREAD

**Issue by idealover** [facebookresearch/xformers#866]
# ❓ Questions and Help
I am getting the error ```Expected batch_size=1 when using block-diagonal bias
  query.shape: torch.Size([4, 4096, 32, 128])
  key.shape  : torch.Size([4, 4096, 32, 128])
  value.shape: torch.Size([4, 4096, 32, 128])``` when using the block diagonal bias - is there any way where I can use a batchsize of 4 when using this?

**Comment by idealover** [comment]
Nvm I have to just change the dimensions

**Comment by qiyan98** [comment]
> Nvm I have to just change the dimensions

Sorry to bother you. But how did you resolve this? Thanks.
