### ISSUE TITLE
[feat] Make the batch dimension broadcastable

### ISSUE THREAD

**Issue by blefaudeux** [facebookresearch/xformers#87]
# 🚀 Feature
Support different key/query/value batch sizes, if 1 or the same value

## Motivation
(popped up when working on [salina](https://github.com/facebookresearch/salina)) PyTorch MHA handles key/query/value with 1 to B batch sizes, will broadcast if in need, We don´t do that and hard crash instead, so the users have to align dimensions from the outside

**Comment by erip** [comment]
I can try to take this. I'll submit a PR later today!

**Comment by erip** [comment]
Maybe to make sure I understand the ask, I see a few things:

1. xFormers doesn't support unbatched (2D) QKVs currently
2. xFormers doesn't support batched, but varying batch sizes between QKV
3. xFormers doesn't support >=4D QKVs (like [torchtext](https://github.com/pytorch/text/blob/main/torchtext/nn/modules/multiheadattention.py#L12-L16))

For the scope of a relevant PR, which aspects would you like to address immediately?

**Comment by blefaudeux** [comment]
sorry for the delay, and thanks for raising that @erip ! I did not explain this issue well enough, sorry about that, it was a brain dump at the time as I was having a look at salina. 2. is the issue I had in mind (one of the batch dims is 1 and we can broadcast it towards the others), but 1. would make sense also, as it's a one liner really. 

The 4D case is basically handled within the MHA if I understood torchtext case correctly (the MHA is the one generating the head dimension), I think that it's simpler not to expose that as it would have consequences on all the attention implementations. The attentions sit below the MHA right now, so they're guaranteed to always get the dimensions in a consistent way, which simplifies them a great deal I believe (and some of them are complicated enough already :D)
