### ISSUE TITLE
xFormers compiled without CUDA extensions 

### ISSUE THREAD

**Issue by almog-co** [facebookresearch/xformers#874]
# 🐛 Bug

On a clean install, xFormers requires `PyTorch 2.0.1` and doesn't support `PyTorch 2.0.1+cu121`. 

## To Reproduce

Occurs on clean install in clean conda environment.

1. `pip install xformers`

```
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1 (you have 2.1.0+cu121)
    Python  3.11.5 (you have 3.11.5)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
```

## Expected behavior

Use PyTorch with GPU support.

## Environment

Please copy and paste the output from the
environment collection script from PyTorch
(or fill out the checklist below manually).

You can run the script with:

```bash
# For security purposes, please check the contents of collect_env.py before running it.
python -m torch.utils.collect_env
```

- PyTorch Version (e.g., 1.0): PyTorch 2.0.1+cu121
- OS (e.g., Linux): Windows 11
- How you installed PyTorch (`conda`, `pip`, source): `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`
- Build command you used (if compiling from source): 
- Python version: 3.11.5
- CUDA/cuDNN version: 12.1
- GPU models and configuration: 3080
- Any other relevant information:

## Additional context
N/A

**Comment by danthe3rd** [comment]
Hi,
You can follow this issue:
https://github.com/facebookresearch/xformers/issues/870
In the meantime, you could try to install the dev builds:
```bash
pip install --pre -U xformers
```
