### ISSUE TITLE
Cannot install xformers on Windows

### ISSUE THREAD

**Issue by DjWarmonger** [facebookresearch/xformers#886]
# 🐛 Bug
I attempted to install xformers in a fresh Conda environment. First as a dependency of [vllm](https://vllm.readthedocs.io/en/latest/getting_started/quickstart.html), then as an individual package, finally tried to build from source. Every time get an eror like this:

```
        File "C:\Users\tomas\miniconda3\envs\llm_server\Lib\site-packages\setuptools\_distutils\util.py", line 139, in convert_path
          raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/__w/xformers/xformers/third_party/flash-attention/csrc/flash_attn/flash_api.cpp' cannot be absolute
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.    
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Could not build wheels for xformers, which is required to install pyproject.toml-based projects
```
Clearly absolute path staring with `/__w/xformers` can't work on Windows.

## To Reproduce

`conda create -n llm_server python=3.11.4`
`conda activate llm_server`
`pip3 install torch --index-url https://download.pytorch.org/whl/cu118`
`pip install llmv`
or
`pip install xformers`

or build from source:
`cd xformers-0.0.22.post3`
`pip install .`

## Expected behavior

Package xformers would install correctly

## Environment

```
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.26.0-rc6
Libc version: N/A

Python version: 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 537.42
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=4401
DeviceID=CPU0
Family=107
L2CacheSize=12288
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=4401
Name=AMD Ryzen 9 7900X3D 12-Core Processor
ProcessorType=3
Revision=24834

Versions of relevant libraries:
[pip3] torch==2.1.0+cu118
[conda] torch                     2.1.0+cu118              pypi_0    pypi
```
## Additional context

I'm new here.

**Comment by Drun555** [comment]
Can you please try to install it with 

```pip install xformers==0.0.20```

I'm also had this issue with 0.0.22.post3. It also broke fresh install process fpr InvokeAI / ComfyUI for me.

**Comment by DjWarmonger** [comment]
That worked fine, thank you :)

vllm still tries to build it from a wheel for some reason, but that's a problem on their side I guess.

**Comment by danthe3rd** [comment]
`0.0.22.post4` was just released, and it should have the wheels for windows built correctly.
We had some temporary issue as we added support for cuda 12
