### ISSUE TITLE
unable to use to PyTorch 1.13.0+cu117

### ISSUE THREAD

**Issue by wendellgithub0206** [facebookresearch/xformers#888]
# ❓ Questions and Help
I have received the following error and would like to ask how to install Xformer that supports Torch 1.13.0 version.
``
 warnings.warn(
2023-10-16 15:05:49 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1 with CUDA 1108 (you have 1.13.0+cu117)
    Python  3.9.18 (you have 3.9.18)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
``

**Comment by XiongFenghhh** [comment]
> # ❓ Questions and Help
> I have received the following error and would like to ask how to install Xformer that supports Torch 1.13.0 version. `warnings.warn( 2023-10-16 15:05:49 | WARNING | xformers | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 2.0.1 with CUDA 1108 (you have 1.13.0+cu117) Python 3.9.18 (you have 3.9.18) Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers) Memory-efficient attention, SwiGLU, sparse and more won't be available. Set XFORMERS_MORE_DETAILS=1 for more details`

hello, did you fix this? I am using cu117 too

**Comment by danthe3rd** [comment]
Hi,
The most recent versions of xFormers only support PyTorch 2.1+.
You can build older versions from source if you have PyTorch 1.13 for instance, but I would recommend that you update PyTorch instead.

**Comment by rishiyama** [comment]
Hello,
I was able to install with the following versions. However, it seems that some functions, including 'efficient_attention', are not supported.

```
pip install torch==1.13.0 xformers==0.0.12
```

**Comment by lw** [comment]
You're using extremely old versions of both PyTorch and xFormers, please upgrade.
