### ISSUE TITLE
How to use FlashDecoding with Xformer

### ISSUE THREAD

**Issue by renfeier** [facebookresearch/xformers#894]
# ❓ Questions and Help
is there a document or example to show the use of FlashDecoding with Xformer

**Comment by danthe3rd** [comment]
Hey,
We have an example here for Llama models:
https://github.com/facebookresearch/xformers/tree/main/examples/llama_inference

In practice, `memory_efficient_attention` will automatically use the Flash-Decoding algorithm if it is supported (it requires bf16/f16, no bias, and A100 or newer GPU)

**Comment by inamori1932** [comment]
May I ask how to obtain the .pth and params.json files from generate.py if I want to accelerate the CodeLlama-7b-Instruct-hf model with this example?
The CodeLlama-7b-Instruct-hf model from huggingface is in .bin format and does not have a params.json file.

**Comment by ChuanhongLi** [comment]
Hi, is these a perf benchmark for FlashDecoding?
