### ISSUE TITLE
build from source "flash attention"error

### ISSUE THREAD

**Issue by suede299** [facebookresearch/xformers#904]
# ❓ Questions and Help
  cl: Command line warning D9002 :ignoring unknown option“-O3”
  cl: Command line warning D9002 :ignoring unknown option“-std=c++17”
  flash_api.cpp
  C:\Users\suede.DESKTOP-UE8CKO3\AppData\Local\Temp\pip-install-envemx59\xformers_cc933148151a4c30a0a9fffbacbb902f\third_party\flash-attention\csrc\flash_attn\flash_api.cpp : fatal error C1083: Cannot open compiler generated file: “”: Invalid argument
  error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
  error: subprocess-exited-with-error
-------------------------------------------------------------
So what can be done about it?
windows
cudaVer 12.1

**Comment by danthe3rd** [comment]
Hi,
We will provide cuda 12.1 builds with Flash-Attention enabled for windows in the next few days :)

**Comment by suede299** [comment]
thanks
