### ISSUE TITLE
`scaled_dot_product_attention` shouldn't have a `causal` flag

### ISSUE THREAD

**Issue by fmassa** [facebookresearch/xformers#91]
The causal flag in https://github.com/facebookresearch/xformers/blob/cc7c8edd6907abdb09d10f60e456e224109a4aca/xformers/components/attention/core.py#L191 was added to enable fast triton kernels for softmax.

I believe we shouldn't have this flag, as it makes it look like we can combine `attn_mask` and `causal`, which doesn't look like it's the case.
Plus, the behavior of `causal` is embedded inside `attn_mask` already.

IMO we should remove `causal`, and instead have a custom class `UpperTriangularMatrix` which can be passed as an `attn_mask`, which gets then dispatched to the efficient causal softmax

**Comment by blefaudeux** [comment]
ah interesting, I went over this part a couple of times recently (with the additive/bool mask change) and it did feel a bit messy. Ok with the proposed solution, in general I think that having types around the mask would help cornering the usecases, beyond causal (ie: convey the fact that it's additive)
