### ISSUE TITLE
Built wheel for torch 2.1.1

### ISSUE THREAD

**Issue by continue-revolution** [facebookresearch/xformers#933]
# ❓ Questions and Help
Can we have a pre-built wheel for torch 2.1.1? I've been waiting for it for a long time.

**Comment by danthe3rd** [comment]
Hi,
Thanks for reporting this. We will try to get dev-wheels (so cuda 12.1) for 2.1.1 next week

**Comment by Fan-Yixuan** [comment]
Looking forward to this!

**Comment by danthe3rd** [comment]
Hi,
We just landed https://github.com/facebookresearch/xformers/commit/be4f584ef8a410038ba74950460d93c794631dc6
Wheels should arrive in ~a few hours

**Comment by continue-revolution** [comment]
I believe that this issue has been completed
