### ISSUE TITLE
What does BMGHK format mean？

### ISSUE THREAD

**Issue by frankxyy** [facebookresearch/xformers#937]
find this in the code multiple times, but currently cannot link them with model parameters like kv_heads，q_heads，kv_len etc.

**Comment by danthe3rd** [comment]
Hi,
You can refer to the documentation: https://facebookresearch.github.io/xformers/components/ops.html?highlight=memory_efficient_attention#xformers.ops.memory_efficient_attention
(Look at "Using with Multi Query Attention (MQA) and Grouped Query Attention (GQA)" and the code snippet below)

But basically:
B = batch size
M = sequence length
G = heads groups (in case of multiquery/grouped query attention)
H = heads per group
K = embedding size per head

The operator supports:
* BMK (although it's not recommended)
* BMHK
* BMGHK (experimental, only supports FW pass for now)

**Comment by frankxyy** [comment]
@danthe3rd got it! Thank you a lot
