### ISSUE TITLE
Comparison with FlashAttention

### ISSUE THREAD

**Issue by xyzhang626** [facebookresearch/xformers#950]
# ❓ Questions and Help

Hey guys I'm some new to xformers. I want to understand what's the relationship between xformers and FlashAttention (the package instead of the paper, I mean). 

Have the xformers already supported Flash Attention (or include the algorithm in `memory_efficient_attention`)? When should I use xformers or flash attention? Flash attention can be easily applied by using monkey patch without modifying the original code while xformers is a bit complicated. But flash attention seems not to support V100. I also want to understand the speed performance comparison between the two accelerators.

Thanks in advance. It's pretty important for me.

**Comment by danthe3rd** [comment]
Hello,
xFormers provides an API `memory_efficient_attention` to run the attention. This API has multiple backends:
- Flash-Attention (A100 or above)
- An xFormers-specific implementation called "cutlass". It's a bit slower than Flash-Attention, but it supports more usecases/devices (eg supports any GPU above P100)

So `memory_efficient_attention` should work with V100

**Comment by xyzhang626** [comment]
Now I understand it. Thanks @danthe3rd !

**Comment by KaiChen1998** [comment]
@xyzhang626 Same question. Since Flash Attention is the primary backend of xformers, if we use torch > 2.0.0 on Ampere GPUs, which means flash attention is adopted by default, is it still useful to additionally utilize xformers?

**Comment by danthe3rd** [comment]
There are some minor additional improvements in xformers that haven't been merged in PT (like the BW pass, avoiding a concatenation of gradients for Q/K/V), and some APIs are not exposed in PT (like local attention).
However for the vast majority, I would recommend to go with PT implementation as it avoids an additional dependency, and you get 99% of the benefits. Especially if you want to add torch compile on top, the PT implementation will work better.

**Comment by VMatrix1900** [comment]
Which version of Flash Attention is used as the backend? Flash Attention 2 or 1.x? AFAIK, flash attention 2 does not support Turing GPU. If I run xformer in Turing GPU, will it call Flash Attention 1.x or cutlass?

**Comment by ai-bond** [comment]
> # ❓ Questions and Help
> 
> Hey guys I'm some new to xformers. I want to understand what's the relationship between xformers and FlashAttention (the package instead of the paper, I mean).
> 
> Have the xformers already supported Flash Attention (or include the algorithm in `memory_efficient_attention`)? When should I use xformers or flash attention? Flash attention can be easily applied by using monkey patch without modifying the original code while xformers is a bit complicated. But flash attention seems not to support V100. I also want to understand the speed performance comparison between the two accelerators.
> 
> Thanks in advance. It's pretty important for me.

I've tried to done it with Volta smem and mma shapes/precision/func restrictions-> [Flash attention 2 for Volta](https://github.com/ai-bond/flash-attention-v100)
