### ISSUE TITLE
PyTorch TransformerEncoder & TransformerDecoder replacement example

### ISSUE THREAD

**Issue by johan-sightic** [facebookresearch/xformers#951]
# ❓ Questions and Help
Hi!
I'm not here do research on Transformers I just want a more efficient replacement for PyTorch `torch.nn.TransformerEncoder` and `torch.nn.TransformerDecoder`. Could we have a minimal example of how to replace those with something as similar and efficient as possible?

Thanks!

**Comment by johan-sightic** [comment]
I did look at the tutorials and examples but everything seems to be outdated

**Comment by danthe3rd** [comment]
Hi,
PyTorch now includes flash-attention by default in those classes I believe, so you don't need to change anything

**Comment by drisspg** [comment]
Yup, FlashAttention will be used for those classes via the [scaled_dot_product_attention](https://pytorch.org/docs/main/generated/torch.nn.functional.scaled_dot_product_attention.html#torch.nn.functional.scaled_dot_product_attention) function.

**Comment by johan-sightic** [comment]
Oh, perfect, thanks!
